### ISSUE TITLE
Switching cameras make caustics explode (HDRP)!?

### ISSUE THREAD

**Issue by dkyeck** [crest-ocean/crest#556] opened 2020-06-19 20:56 UTC
got some issues with caustics and switching between 2 cameras (hdrp): caustics try to adopt to GetCurrentExposureMultiplier() while the camera is tying to adopt the content on screen, so we run into a strange feedback loop here?
this is right after the switch. it gets better within a few frames. but worse if you are close to the ocean's border so it covers a lot of the screen.
![after switch](https://user-images.githubusercontent.com/492095/85178930-f937dd00-b27f-11ea-8065-0b3f2d2e9c31.PNG)

**Comment by daleeidd** [comment] 2020-06-20 02:05
Thanks for reporting. Can you please provide the version of Unity, HDRP and Crest?

**Comment by ftejada17** [comment] 2020-06-20 09:42
Hi!! @daleeidd Something similar happens to me but I only have a camera with Exposure and the Caustic area in some areas where there is shadow generated by the terrain gets very dark when it has somewhat high values of "Caustincs Strength".
It is true that when I lower the value of the parameter the problem disappears, but when it causes the problem, it only does it from some viewing angles ... So I don't know if there is a problem there ...

https://youtu.be/3BSH4mEMNl4

Although perhaps this problem is not really a problem ...
Perhaps it is that the caustic, like the foam, receive shadows from other objects and the ocean does not? that's why this strange result ...

Unity version 2019.4 and Crest version 4.2 (although I imagine that with 4.3 it will happen the same since I think that no correction of this problem is mentioned)

Cheers

**Comment by dkyeck** [comment] 2020-06-20 21:58
version of unity is 2019.3.13f1
hdrp 7.4.1
crest is on latest.
i managed to get around this by dropping GetCurrentExposureMultiplier() and going with:
adjustedLightCol = saturate(i_lightCol) * PI;

**Comment by daleeidd** [comment] 2020-06-21 07:32
Thanks both. I wasn't able to reproduce this. Created a terrain and had shadows etc. I suspect it is adaptive exposure. Are either of you using it?

Either way, I think getting exposure out of the ocean shader is correct.

**Comment by dkyeck** [comment] 2020-06-21 10:08
> Are either of you using it?
yes.

> And what is your exposure value and sun value?
sun goes from 40 - 120000 lux. exposure is set to automatic.

> Either way, I think getting exposure out of the ocean shader is correct.
somehow. caustics right now take the light intensity as input. just like regular lighting.
and this does:
diffuseLighting *= GetCurrentExposureMultiplier(); in ShaderPassForward.

**Comment by dkyeck** [comment] 2020-06-21 10:15
> 
ggg

**Comment by dkyeck** [comment] 2020-06-21 10:18
btw. HDRP comes with an "Indirect Lighting Controller" so _IndirectLightingMultiplier.x shoud be taken into account in the underwater post.

**Comment by ftejada17** [comment] 2020-06-22 00:58
@daleeidd  I also use exposure in Automatic with values of:
- Metering Mode: Center Weighted
- Luminance Source: ColorBuffer
- Compensation: 2
- Limit Min: 7
- Limit Max: 9.75
 
Directional Light lux values of 50000

**Comment by daleeidd** [comment] 2020-06-25 05:11
Does the following work for both of you? It is slightly weaker than before, but no exposure.
```hlsl
half3 adjustedLightCol = i_lightCol * 0.0001;
```

> HDRP comes with an "Indirect Lighting Controller" so _IndirectLightingMultiplier.x shoud be taken into account in the underwater post.

Thanks! We would have to apply it to both the ocean shader and underwater shader from testing for it to be the same. Is there a particular issue you are seeing or is it that you are using that control and want to see it applied to the ocean?

**Comment by dkyeck** [comment] 2020-06-25 09:15
_IndirectLightingMultiplier.x should be picked up by the ocean shader automatically.
in the underwater shader i simply multiply it on top of _AmbientLighting when calling CrestNodeLightWaterVolume()

ambient lighting is baked to probes and the terrain lightmap. so we use  _IndirectLightingMultiplier.x to adjust ambient during the day night cycle.

> half3 adjustedLightCol = i_lightCol * 0.0001;

seems to work

**Comment by dkyeck** [comment] 2020-06-25 09:20
other fixes we had to add to make it work with our day night cycle:

CrestNodeLightWaterVolume.hlsl:
	- lightintensity *= intensityTowardsHorizon; added
	  intensityTowardsHorizon = saturate( dot(i_primaryLightDirection, float3(0,1,0)) * 8 );
	  this fades out the light towards the horizon, so we do not get that heavy pop when the sun goes down.
Ocean.shader:
	- fixed ambient lighting being too dark as it would pick up the indirect multiplier twice (as it is only lit by the sky, ok if it uses probes).
	- foam ambient factor added.

**Comment by daleeidd** [comment] 2020-06-26 06:19
> seems to work

Thank you. This will be out for the next release.

> _IndirectLightingMultiplier.x should be picked up by the ocean shader automatically.

I would think so too. But from my testing this is not the case. It might be my machine, but that would be odd. If I set this to a large value like 100, and I only apply it to the underwater shader, there is a clear difference between above water and below water. If I apply it to both however (in CrestNodeLightWaterVolume) it looks correct.

> this fades out the light towards the horizon, so we do not get that heavy pop when the sun goes down

Thanks! That's a good idea. We never normally did this because Unity never handled this case where the sun was below the horizon. I think we should do this for all pipelines just to be consistent.

> fixed ambient lighting being too dark as it would pick up the indirect multiplier twice (as it is only lit by the sky, ok if it uses probes)

Not sure about this one. Would you be willing to add a separate issue for it?

> foam ambient factor added

Same with this one too. (trying not to make this issue a mega thread)

Alternatively, if you have a bunch of minor issues like the two above, feel free to message me on discord instead.

I really appreciate this feedback. It has been very helpful.

**Comment by huwb** [comment] 2020-06-26 07:23
This is great, thanks all

**Comment by dkyeck** [comment] 2020-06-27 13:53
> I would think so too. But from my testing this is not the case. It might be my machine, but that would be odd. If I set this to a large value like 100, and I only apply it to the underwater shader, there is a clear difference between above water and below water. If I apply it to both however (in CrestNodeLightWaterVolume) it looks correct.

i only tested values between 0.001 and 3.0.
as i wrote: _IndirectLightingMultiplier.x  should be picked up by the ocean shader automtically (in one of the lighting steps hdrp adds: pre, post, whatsoever) but i might be wrong about this.
and we only got glowing underwater ambient but no glowing above water ambient.

**Comment by dkyeck** [comment] 2020-06-27 14:01
> Not sure about this one. Would you be willing to add a separate issue for it?

done.

**Comment by daleeidd** [comment] 2020-07-07 09:16
@dkyeck 4.4 has been release which includes a few fixes and suggestions you made. I'll leave this open as I would like to hear your feedback.

**Comment by daleeidd** [comment] 2020-07-29 14:14
I'll close this for now. Feel free to respond and I will get the notification.

**Closed by daleeidd** 2020-07-29 14:14 UTC
Labels: HDRP, bug
