### ISSUE TITLE
An idea to tickle  ur superior brains guys. ( procedural wave splashes fx )

### ISSUE THREAD

**Issue by VizzzU** [crest-ocean/crest#467] opened 2020-04-05 09:54 UTC
I guess i am not alone . It would be awesome to build a procedural wave splash generator . I have included vidéo example links. A basic splash generator would also be very usefull . 

https://www.youtube.com/watch?v=8ok9Ra6WTFU
https://www.youtube.com/watch?v=OQ3D0Q5BlOs

**Comment by huwb** [comment] 2020-04-05 11:19
Hi VizzzU! Nice to hear from you!

This is a duplicate of issue #93. I posted your videos there, and I posted an update on that thread, please take a look there!

**Closed by huwb** 2020-04-05 11:19 UTC
