### ISSUE TITLE
[HDRP] Editor crashes on Mac

### ISSUE THREAD

**Issue by Shizzane** [crest-ocean/crest#580] opened 2020-07-09 16:49 UTC
Hi,

I've worked through Crest most of the day and got things figured out for the most part. I've to restart a few times. It's a really nice water plugin, I think it's the only one available right now for HDRP. 

My issue (on Mac running latest OS) in Unity 2019.4.2f1 HDRP is:

I'm not sure if this is the issue but it seems like Depth Cache is causing my mac to crash to a restart. 
It does crash often on my Mac but I understand it's still under development. 

What settings can I play with to tone down the overhead a bit if any?

Also I have the water interaction scripts on my player for affecting the water when they are in it, but do you currently have a splash effect? I suppose I could do my own with a particle...just wondering. 

Finally, is there a way for the foam on the shoreline script to interact with the interaction script so that the foam moves when the player walks through it in shallow water?

Cheers,
Shane

**Comment by huwb** [comment] 2020-07-11 08:41
Hello, sorry to hear this. Which version of crest are you on?

It should not be crashing as far as im aware. Is it taking down your editor?

@daleeidd are you seeing issues like this on Mac?

I'm going to target this issue towards your instabilities if thats ok. I'll answer the other questions briefly here but lets break them out into their own issues if we want to go deeper:

* Performance - there was a significant performance issue in 4.3, besides that there is a section in the userguide about performance
* Particles - there is an experimental branch for this and you can see how we did it: https://github.com/crest-ocean/crest/pull/501
* Player interaction - we have a dynamic wave system (demonstrated in boat.unity) which may achieve this, depending on what you need

**Comment by daleeidd** [comment] 2020-07-11 12:31
@Shizzane Can you please provide details on your Mac hardware?

> are you seeing issues like this on Mac?

I was getting these issues on my 2018 Mac Mini when I had it (I had crashing issues for all pipelines). I haven't had any issues on my older 2014 MacBook Pro.

**Comment by Shizzane** [comment] 2020-07-11 12:58
Running 4.4. 

Nope it's not taking down editor. 

Ok thank you I will check out the experimental branch on splash/particles and player interaction for foam movement. 

@daleeidd Actually I was thinking this earlier...I'm running on a Core i7 Mac Mini 2018, 3.2Ghz, 32 GB ram and an EGPU Razor Core X with a Radeon RX5700 8MB ram.

So it's a decent unit but i was reading that some folks swapped out the stock thunderbolt cable for an apple one and there was no more crashing. So that might actually be my issue.

**Comment by daleeidd** [comment] 2020-07-11 13:10
> EGPU Razor Core X

I had one of those too. But with an RX 580. Interested to see how you go.

Do you see anything GPU related in the Console.app when running Unity with Crest? If you open it and paste "message type:error" and then "message type:fault" it will filter out everything except errors and faults. They might not appear straight away so leave the Console.app running in the background.

**Comment by Shizzane** [comment] 2020-07-11 13:14
Hmm yeah lots lol. I'm an artist not a programmer so I'm not sure which ones are related to Crest if at all. 

error	10:11:50.298922-0300	mobileassetd	_MobileAssetUpdateClientUsage_block_invoke: Could not get accessing clients is nil
error	10:11:50.299010-0300	mobileassetd	_MobileAssetUpdateClientUsage_block_invoke: Could not get accessing clients is nil
error	10:11:52.534953-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:11:53.744172-0300	suggestd	SGNamedEntityPlugin failed to fetch user activity: Error Domain=NSCocoaErrorDomain Code=4608 "Handoff couldn’t be completed." UserInfo={NSUnderlyingError=0x7f8d511a3a70 {Error Domain=UAContinuityErrorDomain Code=-107}}
error	10:11:57.533979-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:11:57.906677-0300	com.apple.DictionaryServiceHelper	_DownloadCatalogFile for 'com.apple.MobileAsset.DictionaryServices.dictionaryOSX' (sync=0) start
error	10:11:57.918642-0300	nsurlsessiond	remoteObjectProxyWithErrorHandler error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.cache_delete.public was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.cache_delete.public was invalidated.}
error	10:11:57.918674-0300	nsurlsessiond	CallBlockWithProxy remoteObjectProxyWithErrorHandler(com.apple.cache_delete.public) error: Error Domain=CacheDeleteErrorDomain Code=2 UserInfo={NSUnderlyingError=0x7fc6be40f370 {Error Domain=NSCocoaErrorDomain Code=4099 UserInfo={NSDebugDescription=<private>}}}
error	10:11:57.918766-0300	nsurlsessiond	Failed to get available space for volume <private>: Error Domain=CacheDeleteErrorDomain Code=2 UserInfo={NSUnderlyingError=0x7fc6be40f370 {Error Domain=NSCocoaErrorDomain Code=4099 UserInfo={NSDebugDescription=<private>}}}
error	10:11:57.918806-0300	nsurlsessiond	Task <09CCC10E-2E77-420D-81E3-873DC21FCED0>.<16> unable to get the space available on disk
error	10:11:57.919224-0300	nsurlsessiond	Task <09CCC10E-2E77-420D-81E3-873DC21FCED0>.<16> finished with error [6] Error Domain=_nsurlsessiondErrorDomain Code=6 UserInfo={NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, _NSURLErrorFailingURLSessionTaskErrorKey=<private>}
error	10:11:58.925246-0300	coreduetd	Prediction is unavailable because no data was provided.
error	10:11:58.926177-0300	coreduetd	Prediction is unavailable because no data was provided.
error	10:11:59.021862-0300	nsurlsessiond	Client <private> does not support app wakes, but it is still running. Will attempt to get file descriptor for download file.
error	10:11:59.023507-0300	mobileassetd	-[DownloadManager lastModifiedDateFromResponse:]: No value for key Last-Modified
error	10:11:59.035190-0300	com.apple.DictionaryServiceHelper	_DownloadCatalogFile for 'com.apple.MobileAsset.DictionaryServices.dictionaryOSX' (sync=0) finished result=0
error	10:12:02.527159-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:07.527353-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:08.687253-0300	kernel	Sandbox: bluetoothd(144) deny(1) mach-lookup com.apple.server.bluetooth
error	10:12:13.025947-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:18.028356-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:19.654545-0300	kernel	Sandbox: bluetoothd(144) deny(1) mach-lookup com.apple.server.bluetooth
error	10:12:19.833717-0300	sharingd	Trying to grab power assertion while we already have one
error	10:12:22.527085-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:25.126095-0300	sharingd	Trying to grab power assertion while we already have one
error	10:12:27.528261-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:31.797229-0300	sharingd	Trying to grab power assertion while we already have one
error	10:12:32.527530-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:34.890325-0300	sharingd	Trying to grab power assertion while we already have one
error	10:12:36.676321-0300	sharingd	Trying to grab power assertion while we already have one
error	10:12:37.523802-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:42.525470-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:48.023636-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:53.022676-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:12:58.022517-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:13:03.021512-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:13:07.521872-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:13:12.521739-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>
error	10:13:12.599817-0300	sharingd	Trying to grab power assertion while we already have one
error	10:13:17.988800-0300	deleted	unable to create CacheDeleteDaemonVolume for <private>

**Comment by daleeidd** [comment] 2020-07-11 13:54
The faults will look something like this:
void IOAccelFenceMachine::fence_timeout(IOTimerEventSource *): AMDRadeonAccelerator prodding blockFenceInterrupt
void IOAccelFenceMachine::fence_timeout(IOTimerEventSource *): IntelAccelerator prodding blockFenceInterrupt
void IOAccelEventMachine2::signalHardwareError(eRestartRequest, int32_t): GPURestartSignaled stampIdx=2 type=2 prevType=0 

No rush to try and reproduce. As you are using Unity, have the Console.app open and check it when you see any hangs in the editor. It will be better if only the fault filter is applied since errors are kind of like warnings and are numerous.

**Comment by daleeidd** [comment] 2020-12-15 01:25
I'll close this one for now. Please comment if the issue still persists. I recommend continuing to update Unity and MacOS to the latest. MacOS and Unity isn't the most stable from my experience. As a workaround, there is a proxy plane option on the OceanRenderer if performance or stability is an issue. Also, performance can be improved in the editor when animated materials is disabled (option is found on the scene view). Lastly, it can never hurt to also submit a bug report to Unity.

**Closed by daleeidd** 2020-12-15 01:25 UTC
Labels: HDRP, metal
