### ISSUE TITLE
Reflection objects are not created, when instance of crest is changed

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#623] opened 2020-08-19 21:10 UTC
**Solution**
Move code from OceanPlanarReflection.Start to OceanPlanarReflection.OnEnable.

Reason: I have a setting to turn reflection on/off. So, reflection script is disabled if that switch is off.

**Comment by daleeidd** [comment] 2020-08-19 22:10
Is this the same issue as #576?

**Comment by klauskobald** [comment] 2020-08-20 13:17
ah, yes sorry!

**Comment by daleeidd** [comment] 2020-08-20 15:36
No worries. Closing as is duplicate of #576

**Closed by daleeidd** 2020-08-20 15:36 UTC
Labels: duplicate
