### ISSUE TITLE
[HDRP] Shader Errors on Unity 2020.2 Beta & HDRP 10.1.0+ Versions

### ISSUE THREAD

**Issue by TeorikDeli** [crest-ocean/crest#698] opened 2020-11-24 12:27 UTC
**Describe the bug**
On the beta version of Unity 2020.2 with HDRP 10.1 (and 10.2), Crest shaders gives shader error and doesn't work. It is most probably because of the HDRP 10.1 changes (for example: Removed BLEND shader keywords.). I was using Crest without any problem on Unity 2020.2.0b9 and HDRP 10.0.0.preview27 before. This is not an urgent problem of course, because these versions are still in beta =)

**Logs**
```
Shader error in 'Crest/Ocean': undeclared identifier '_BlendMode' at HDRP_Test/Library/PackageCache/com.unity.render-pipelines.high-definition@10.2.0/Runtime/Material/Material.hlsl(51) (on d3d11)

Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR
Disabled keywords: LOD_FADE_CROSSFADE INSTANCING_ON CREST_FOAM_ON CREST_CAUSTICS_ON CREST_FLOW_ON UNITY_NO_DXT5nm UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30
```

Actually, there are more shader errors (One of them is in the some Shadow shader I think), but I can't reproduce the log right now.

**Versions**
HDRP 10.1.0+ and Unity 2020.2.0b12 (No problem in HDRP 10.0.0.preview27 and Unity 2020.2.0b9)

**Comment by emaber** [comment] 2020-11-24 18:32
Came here to report the same problem! Thank you for reporting it.
We had this problem since b10 and it's preventing us to upgrade as we are dependent on features in 2020.2 Beta.

**Comment by daleeidd** [comment] 2020-11-25 03:08
Will be fixed for next release (4.7).

**Comment by daleeidd** [comment] 2020-12-15 00:54
Crest 4.7 is out so I will close this. Thank you for reporting.

**Closed by daleeidd** 2020-12-15 00:54 UTC
Labels: HDRP, bug

**Comment by NeistH2o** [comment] 2020-12-15 19:41
I'm using HDRP 10.2.0 and I get the following error after updating:
`Shader error in 'Crest/Ocean': undeclared identifier '_BlendMode' at /[...]/Library/PackageCache/com.unity.render-pipelines.high-definition@10.2.0/Runtime/Material/Material.hlsl(51) (on d3d11)`

Maybe it has to do with something that changed in 10.2.0, the [changelog](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.2/changelog/CHANGELOG.html) mentions this:
> Removed _BLENDMODE_PRESERVE_SPECULAR_LIGHTING keyword from shaders.

**Comment by NeistH2o** [comment] 2020-12-15 22:17
I had to delete the package from the asset store cache in order to get it to import the 4.7 instead of the 4.6, I don't know if it was a bug with unity's package manager but I spent 3 hours trying to figure out why I still had the same error, so just in case it happens to someone, the asset store cache is at `C:/Users/[...your user folder...]/AppData/Roaming/Unity/Asset Store-5.x`

**Comment by brucekirkpatrick** [comment] 2020-12-26 07:03
I was debugging this issue on Crest HDRP 4.7 tonight, where you said this was fixed but unfortunately I figured out how to cause the problem on this version.  I never had a previous version of Crest HDRP 4.7.   I noticed that the demo scene doesn't have the problem with the horizon line gap after reading that you said it is very hard to reproduce.   I was able to isolate that what you did to get rid of this horizon gap was to reduce Spectrum 512 to a very low value.  If you put spectrum 512 above 60%, it reintroduces the gap.   What I did to get myself in trouble was build a from scratch crest setup, and I thought that it didn't make sense for the 512 spectrum to be less then the rest of the curve, so I made it slightly more then 256, and didn't realize this caused the gap issue.   If 512 can't function properly in the range that the interface allows, maybe you should constrain its value, or automate a safe min() value at runtime.   The problem also only appears when Shape Gerstner Batch script is enable.   I don't think LOD values matter.  I copied the same LOD values as demo and it persisted with the same horizon gap line problem.   Anyway, I'm happy I was able to come up with the reason it breaks.  I hope anyone else finding this thread, will be able to fix it too.

**Comment by brucekirkpatrick** [comment] 2020-12-26 07:41
posted in wrong place, deleted comment.
