### ISSUE TITLE
GerstnerPatch waves not working in shallow water.

### ISSUE THREAD

**Issue by andrew-sidereal** [crest-ocean/crest#643] opened 2020-09-02 05:10 UTC
**Describe the bug**
GerstnerPatch local waves don't work in shallow water in game-mode, but they show up as expected in scene mode. Screenshots capture it well.

**Screenshots / video**
In scene-mode, waves are placed all the way up to the shoreline and appear okay: https://i.imgur.com/hvNxJbO.png
In game-mode, the waves only appear in the deeper water and don't go up the shore, leading to an odd calm area between the waves and the shore.
https://i.imgur.com/S7MPSdq.jpg

**Versions**
Latest master commit.
Unity 2019.4.4
Built-in Pipeline

**To Reproduce**
I copy & pasted the GerstnerPatch from the Boat scene.

**Comment by huwb** [comment] 2020-09-02 07:11
That seems like a 'depth cache' issue. As far as i can tell, the behaviour you're getting in game is by design - big waves dont travel in to shallow water.

I'm not sure why the depth cache is not working for you in edit mode. Maybe attach your settings on the depth cache?

Either way if you want the first image result, remove the depth cache or set the layers so that that geometry does not contribute to the cache.

**Comment by andrew-sidereal** [comment] 2020-09-02 07:39
That makes sense. Thanks for helping me understand what's going on. I set
the depth cache at run-time so it makes sense that it's not showing up in
the scene mode, FWIW.

**Comment by daleeidd** [comment] 2020-09-02 15:57
Perfect. I'll close this issue :)

**Closed by daleeidd** 2020-09-02 15:57 UTC

**Comment by andrew-sidereal** [comment] 2020-09-02 18:24
One thought -- how difficult is it to have the wave height just reduce in
magnitude in shallower water, rather than cease? That would provide a
better appearance of the waves washing up on the shore.

**Comment by daleeidd** [comment] 2020-09-15 21:21
In the _SimSettingsAnimatedWaves_, try reducing the _Attenuation In Shallows_ property.
