### ISSUE TITLE
[HDRP] Underwater effect not displayed through high bumps of water

### ISSUE THREAD

**Issue by Auxilinaut** [crest-ocean/crest#458] opened 2020-04-01 02:29 UTC
**Describe the bug**
The underwater effect is not displaying when moving the camera through large bumps/wave peaks. It does display the closer/lower the camera is to the sea level.

**Screenshots / video**
![image](https://user-images.githubusercontent.com/6234363/78091929-42bd0e00-739c-11ea-8238-2e6b18862e24.png)

**Log**
[editor-log.txt](https://github.com/crest-ocean/crest/files/4412422/editor-log.txt)

**Versions**
Unity 2020.1.0b2/2020.1.0b3 HDRP 8.0.1

**To Reproduce**
1. Open boatdev/scenes/boat.unity
2. Click play and drive the boat toward one of the high bumps in the water
3. Observe the lack of underwater effect while moving the camera through the water peaks

**Platform**
 - Editor
 - Windows 10 Education 1903

**Hardware**
Ryzen 5 1600, 16GB Corsair Vengeance, EVGA RTX 2070 Super

**Comment by daleeidd** [comment] 2020-04-01 03:08
Thanks for reporting. The underwater water effect is currently set to be disabled if the viewer is 2 metres above the surface. We should expose this property for those who need it.

But 2 metres should also work in this scenario. I tested it on built-in and the underwater effect works with a check of 1.5 metres.

I just checked and it looks like height queries aren't working properly for animated waves added using inputs. The `ViewerHeightAboveWater` remains the same when flying through these bumps.

**Comment by daleeidd** [comment] 2020-04-01 05:10
There seems to be more going on here. It also looks like a displacement issue too. High chop values on larger waves produce inaccurate results.

The local gerstner waves don't change the value even with no chop. But the water height objects (plane and sphere) work perfectly fine.

Reproducible in Editor and Standalone on MacOS.

**Comment by huwb** [comment] 2020-04-01 20:20
Thanks @daleeidd . It might be the iteration count in the query displacements compute shader, similar to what you found with the clipping. Could you please try with a higher count?

**Comment by daleeidd** [comment] 2020-04-02 03:42
It didn't have an effect. I tried increasing it to 20. I also tried unrolling the loop manually.

I realised I have incurred this issue before. It is related to this [issue](https://github.com/cowhunt/crest-srp/issues/22). By passing a minimum length value of 2 for the viewer for the displacement sampler, the height now works correctly.

I tested further with extreme displacements (large waves with high chop), and I needed to increase this value for it to continue to work correctly.

**Comment by huwb** [comment] 2020-04-02 18:23
Thanks @daleeidd thats very useful.

I can repro it here, this is a good setup to debug. My sphere has the sample height script on it so it tracks the surface, and also it shows the local collision area using that other component.

![image](https://user-images.githubusercontent.com/939901/78280218-a7997500-7510-11ea-9317-f5496d47087e.png)

Think i found a couple of issues. Firstly the computation of minSlice in CSMain() of QueryDisplacements is very dangerous as if minGridSize is 0, that will compute a log of 0 which is a NaN, which may be causing a crash that  @mattmac reported which seemed to have NaNs from the query shader. There's also a potential log(0) in PosToSliceIndices.

Secondly, PosToSliceIndices() is broken but i cant quite work out why. If the minSlice argument is small, it seems to kill the displacements. Can you poke around in this function?

(HDRP may have slightly different code for the height queries, it would be good to check and unify as part of this later)

**Comment by daleeidd** [comment] 2020-04-02 20:05
Fixed-ish...

The order of the `PosToSliceIndices` parameters have changed. `minSlice` is going to the wrong parameter but fixing it made it worse. Except after the next fix...

The built-in version of that function uses `_LD_Pos_Scale[0].z`. By passing that through from the compute functions and using it for `radius0` instead of `minScale` the height queries seemed to work again.

Also, that debug setup completely freaked Unity on MacOS. Hard crash. Even with the eGPU running.

**Comment by huwb** [comment] 2020-04-02 21:22
Ok hopefully we're circling in on our metal issues at the same time then!

Could you get this pushed to a branch/pr, i think i need to go through the changes you mentioned above.

**Comment by daleeidd** [comment] 2020-04-03 03:40
Sure. I sent the branch to you on Discord

**Comment by daleeidd** [comment] 2020-04-22 12:56
This has been fixed in 4.1. Please reopen if you still experience issues.

**Closed by daleeidd** 2020-04-22 12:56 UTC
Labels: HDRP, bug
