### ISSUE TITLE
Question: How do I get the hands to create ripples on ocean surfase in VR

### ISSUE THREAD

**Issue by EcoEditor** [crest-ocean/crest#381] opened 2019-12-26 12:43 UTC
Hello Huw, @huwb  

I'd like to ask you for your help regarding the Object Interaction with water.
In the demo scene three boats, the boats interact with water and create a "path" of interaction (small wave and foam) behind and in front of it.
![image](https://user-images.githubusercontent.com/42212240/71473992-1b293900-27e2-11ea-8056-7c9e5532f13b.png)

I've been trying to get my VR hand to interact with the water. This are the steps:
1. First the scripts responsible for Object Interaction is: RegisterDynWavesInput.cs (inherits from RegisterLodDataInput.cs and relevant interfaces + OceanRenderer.cs (variables as scale). Also the comment says: "Attach this GameObjects that you want to influence the sim to add ripples etc."
Seems that the "ObjectWaterInteraction.cs" and the "BoatAlignNormals.cs"/"BoatProbes.cs" will not be relevant in my case - since the player will initiate the movement.

2. After attaching this script to the VR hand, I get a very frequent and large wave input, also the wave is spiking regardless of the y position of the hand. 

3. Reading further in RegisterLodDataInput.cs, showed me that the material on the interacting object need to have a variable of "_Weight", since unity's "default material" has no such variable, I've created a new material with the DynWavesObjectInteraction.shader

4. The spiking waves disappeared, and the hands didn't affect the water at all. 

5. I've played with the shader properties and couldn't set it properly to interact with water.

6. Also it occurred to me that placing the object on the ocean relates with water interaction registered. For example, in threeboats scene, if the medium boat is too far away from the original position (400,0,400), it will not create ripples. I wonder what variable on the Ocean gameObject is responsible for this behavior. 

My goal is to create ripple based on hand movement, could you please guide me to the relevant scripts, scriptable object, components, shaders, video tutorial?
Thanks
L.

**Comment by huwb** [comment] 2019-12-26 17:29
Hello, I've created an experimental feature to make this easier. I modified ObjectWaterInteraction.cs to, if it does not find a boat script, attach an 'adaptor' script which will feed it the required information based on the parent object's motion.

20fe01ed15871cf756d379f23fb2cccfc190d3db

I have placed an "AnimatedObject" gameobject that demo's this. There is nothing special about this GameObject - it could be animated from any source, including moving the object manually in the scene view. It has a sphere shaped interaction object as a child which drives the interaction. 

Would it work to use the finger objects etc as the parent (instead of AnimatedObject)?

(6. the system has levels of detail from the LOD system, there is less detail in the distance and the waves are less visible. it's less an explicit or desired behaviour and more a limitation of the system)

**Comment by EcoEditor** [comment] 2019-12-28 09:05
Hi @huwb 
I'm a bit new to the github terminology.
You've added a fork link I think (20fe01e) , what to do with it?
Meanwhile downloading the project again.

**Comment by EcoEditor** [comment] 2020-01-01 15:06
Hi Huw,

Thanks so much for the added scripts. I've tested it with VR hands (Oculus) and it's possible now to create waves and foam on the water surface by hand movement. 
However I had to change AnimatedObject scale to 0.1, and make sure to get the same effect.
My guess here: the denser the ocean's vertices the more efficient smaller objects are. 
I've lowered the LOD to 2 (instead of 7) and it seemed to help. 
also I've lowered the FactorOrthogonal to 0.5 on the WaterInteractionBoatProbes material. 
Still I have slightly high waves and my camera often "goes" under sea. 
Will let you know how this works for me.

**Comment by huwb** [comment] 2020-01-01 16:21
> However I had to change AnimatedObject scale to 0.1, and make sure to get the same effect

So you had to change the scale to match the fingers? I think thats by design but just checking if i understood.

I'll close this out. Thanks!

**Closed by huwb** 2020-01-01 16:21 UTC
Labels: question

**Comment by EcoEditor** [comment] 2020-01-01 16:57
Yes I had to change the scale to mach the hands. 
I didn't go as far as finger, and chose a more robust approach of scaling for the hand.
Is it even possible to effect the water by such a small scale as finger tip? 
In the picture below: the player is holding a "AnimatedObject" sphere, and the ratio of vertices is visible Hands VS. Ocean

![image](https://user-images.githubusercontent.com/42212240/71643904-5aff8d00-2cc8-11ea-9f3b-e0398b14f3c5.png)
