### ISSUE TITLE
Errors after enabling ocean in runtime

### ISSUE THREAD

**Issue by EvgeniusL** [crest-ocean/crest#285] opened 2019-07-05 06:19 UTC
In my scene, there is no player at start. The ocean is disabled. When the scene is started, the game connects to server, instantiate player and then enables the ocean. Ocean shows correctly but with two errors:

NullReferenceException: Object reference not set to an instance of an object
Crest.ShapeGerstnerBatched.LateUpdate () (at Assets/Crest/Crest/Scripts/Shapes/ShapeGerstnerBatched.cs:346)

NullReferenceException: Object reference not set to an instance of an object
Crest.LodDataMgrSeaFloorDepth.BuildCommandBuffer (Crest.OceanRenderer ocean, UnityEngine.Rendering.CommandBuffer buf) (at Assets/Crest/Crest/Scripts/LodData/LodDataMgrSeaFloorDepth.cs:35)
Crest.BuildCommandBuffer.Build (Crest.OceanRenderer ocean, UnityEngine.Rendering.CommandBuffer buf) (at Assets/Crest/Crest/Scripts/BuildCommandBuffer.cs:38)
Crest.BuildCommandBuffer.LateUpdate () (at Assets/Crest/Crest/Scripts/BuildCommandBuffer.cs:85)

I'm not sure, but seems like it affects buoyuancy. I've tried the same BoatProbes object in my scene and in demo scene of Crest Ocean. In demo it floats correctly, but in mine it stabilize too much and don't move if no forces applied, even with big waves. 

I'm using Unity 2019.1.6f, LWRP 5.16.1, and Crest Ocean LWRP from 08.05.19 (I can't find where the version is written), on standalone Windows 10.

**Comment by huwb** [comment] 2019-07-05 07:04
Hm i should probably write the version into the readme each time, will do that in the future.

I still need to know what you have at that line to be sure? Is it this:

            while (_wavelengths[componentIdx] < minWl && componentIdx < _wavelengths.Length)

If so then there might be some weird update order thing happening.. Could you please try changing the if() statement at the top of the function (LateUpdate) to this:

           if (OceanRenderer.Instance == null || _wavelengths == null)

That would verify this is the problem and maybe even fix it, but i'd be confused at why its happening at all!

**Comment by EvgeniusL** [comment] 2019-07-08 05:23
Yes, it's the correct string, and yes, your fix fixed the error. But the second exception still exists. And I can't test if it fixed buoyancy so far. I will comment as soon as I test it.

**Comment by huwb** [comment] 2019-07-08 14:24
I've repro'd this and am experimenting with solutions.

**Comment by huwb** [comment] 2019-07-08 21:41
Oops it auto-closed this issue - reopening.

This issue should be resolved on the github version now, but ill need to post a new LWRP version. there's a bit of a big merge job but hopefully it gets done in the next few days.

**Comment by EvgeniusL** [comment] 2019-07-09 07:38
Great! Thanks for a quick fix! 
Is it really affected buoyancy, or this problem has another root?

**Comment by huwb** [comment] 2019-08-20 07:18
Oh just realised i can close this, was fixed in Crest LWRP 2.0.

The problem was with how ocean inputs were registered. It should be much more robust now. Any observation with buoyancy was likely a side effect, not the root cause.

**Closed by huwb** 2019-08-20 07:18 UTC
Labels: bug
