### ISSUE TITLE
Simulating water for lakes, marsh or rivers

### ISSUE THREAD

**Issue by Shizzane** [crest-ocean/crest#581] opened 2020-07-11 13:07 UTC
I was playing with the shallow water script but it's still using the data from the main ocean rendered. So I was just wondering if there's a feature in the works to simulate lakes, rivers, ponds etc? (Water colour, wave height etc independent from the ocean). Or perhaps I could just use a different asset. Only thing is my project is HDRP and you guys seem to be the only one who support it at the moment. 

Cheers,
Shane

**Comment by daleeidd** [comment] 2020-07-11 13:15
Thanks for your interest in that feature. There is #361 being actively worked on. I recommend having a look. I'll close this as it is a duplicate of #345

**Closed by daleeidd** 2020-07-11 13:15 UTC
