### ISSUE TITLE
Beaufort Wind Force Scale

### ISSUE THREAD

**Issue by vertas123** [crest-ocean/crest#577] opened 2020-07-08 12:55 UTC
It is a good idea to somehow corellate the wave amplitudes of a specified spectrum(let's say WavesModerateSmooth) with an approximate value in beaufort wind scale

For example if weight of waves is 0.2 then what's the equivalent in beaufort scale that produces a wave with the same amplitude?

**Comment by daleeidd** [comment] 2020-07-08 15:53
This is a planned feature. We have no date as to when it will happen. Closing as duplicate of #416

**Closed by daleeidd** 2020-07-08 15:53 UTC
