### ISSUE TITLE
Reflections on Ocean Surface that are from the bottom of the horizon in Crest HDRP

### ISSUE THREAD

**Issue by ftejada17** [crest-ocean/crest#461] opened 2020-04-02 13:35 UTC
In this video I show some "spots" of reflections that the ocean surface receives: 
https://youtu.be/V2Z4fDVfRFw

For what has been investigated with and spoken with huw are from reflections that come from below the surface of the ocean, that is, from the lower part of the horizon in the Sky.

This problem can be alleviated by putting the color below the horizon in the Sky a color similar to that of the top of the Sky.
The problem comes when you have a terrain and ReflectionProbe that captures Sky and Terrain to show reflections.

In this case it does not work to change the color of the Sky below the horizon since the reflections below the horizon will be taken from Terrain. And I can't change the terrain textures so you don't get those reflection "spots".

I am not a Shaders programmer so excuse me if this idea is nonsense ... It is for the problem of "spots of reflection" to understand us ...

Can we access the reflection value that Unity returns that corresponds to the reflection that CrestHDRP interprets as below the horizon? Not to the entire reflection that Unity returns, only to the value of the concrete reflection that CrestHDRP interprets as below the Horizon.
I hope you understand me

If we could, we could enable a public variable in the Crest HDRP Shader to manipulate its value ...
Variable would go from value 0 to 1 and would be multiplied by the value of the specific reflection "reflection spot" to attenuate that "reflection channel" without losing amount of reflection from other parts of the Ocean such as (sky and others above the surface)

Makes sense?
This does not solve the problem but gives each user freedom to modify it in real time using script according to their needs, while a suitable solution to this problem is found

**Comment by huwb** [comment] 2020-04-02 21:25
To add a note, a way that we might tacke this is to set the Specular PBR value to 0 if the reflection ray is going below the horizon. This would dial down the reflection which may make the water appear blue which may be a good approximation.

**Comment by huwb** [comment] 2020-04-15 17:50
We haven't looked at this yet but its on our list. We've had a high volume of requests/bugs with the new release, apologies for not getting to it yet. I'll post back when we have news.

**Comment by ftejada17** [comment] 2020-04-16 19:52
Ok. Thank you @huwb !!
I have continued to test and reflections that are not generated by heaven also seem to be wrong. I am referring to the reflections of other objects (rocks, cubes of color, vegetation, etc.).
Rather they seem like spots in the ocean. I don't know if it's Unity's problem, or how Crest interprets the data that comes from Unity, but it seems that something is wrong in my opinion.

I would like you to evaluate it and see if it is an error that is happening.

I have recorded some videos to show what I mean. For example, in the following video we see **Crest HDRP** showing the reflections of a red cube:
[https://youtu.be/SFU8VHe6Rwg](url)

And in this video the reflections of the ocean of **another asset** with the same red cube are shown:
[https://youtu.be/vy1Vd9iRs8k](url)

In this video **Crest HDRP** tries to show the reflections of a rock, but frankly it is not appreciated, since the tests I have done will only show depending on where the sunlight comes from. That if, when the reflections are shown, they do not seem very realistic:
[https://youtu.be/PSjJ9BhK3us](url)

And in this other video I show the same rock but with the reflections of **another asset** and they seem more natural and realistic:
[https://youtu.be/Yuh1Km8J0Us](url)

In this video I show **Crest StandardPipeline**, but a version from the beginning of 2019, in which I show the normal reflections with your Reflection script that is added to the camera and the normal reflections without that script. I show the same red cube and a terrain. And all the reflections show up pretty well:
[https://youtu.be/rnA9nxASeoQ](url)

I think with these videos you can see that something is wrong with the reflections of the sky and in general with any object in Crest HDRP. 

I hope this helps you find if there is a problem.
Cheers

**Comment by huwb** [comment] 2020-04-18 14:14
Thanks very much for this @ftejada17 . We will try to tackle this for Crest HDRP 4.3

**Comment by huwb** [comment] 2020-04-18 18:17
I went through the above. The first thing to note is that we don't do any shading in Crest HDRP. We generate the surface normals and give them to HDRP, and HDRP does the shading. What this means is that if you create any shadergraph with a normal map on it, it should reflect the same as crest. I've done a test right now where i turn off the gerstner waves and so its just normals, and then i create a simple shadergraph that uses the same normal map, and the result matches.

So it might be that some of the above issues are due to the reflection setup in HDRP. How have you set up reflections in the above? Planar reflection, or a reflection probe?

In each case it would be useful to hook up a simple shadergraph which applies our wave normal map and apply it to a plane in the world and see what it's reflections look like. This is the shadergraph i'm using here:

![image](https://user-images.githubusercontent.com/939901/79650021-e2eea180-81a8-11ea-9184-a8ada614e790.png)

If you find that a simple shadergraph gives good results but ours does not, it might be an issue with how we're computing normals.

**Comment by huwb** [comment] 2020-04-18 18:23
There might be multiple issues in this thread. If we find multiple issues then we should break them out into separate issues so that we can close them, and so we can find them in the future if needed.

From now on i'll write about the original issue (title of this issue) - reflections below horizon.

Using the above shadergraph i confirmed that this is a general problem rather than something specific to crest. However as i noted it might be we can remove the below horizon reflections with some custom code.

Test with simple shadergraph, without any custom changes:

![image](https://user-images.githubusercontent.com/939901/79652124-7d4ee500-81a9-11ea-8fcb-f7e8d294b061.png)

Ramp down occlusion based on reflection normal:

![image](https://user-images.githubusercontent.com/939901/79654093-1251de00-81aa-11ea-837e-629bc69ebef2.png)

Its quite fiddly to get right but it seems to be promising at least.

**Comment by ftejada17** [comment] 2020-04-19 04:46
Hi @huwb !!!
Is this normal that I show in the video below ???? I don't know if I did something wrong but just copy the shader that you put in the photo above in ShaderGraphs and when you touch the "NormalScaler" parameter the reflections are unreal. Have I done something wrong or is there a problem?

https://youtu.be/YxfbBBjW3bA

On the other hand, to the question you asked me: "How have you set up reflections in the above? Planar reflection, or a reflection probe?"
I use Reflections Probes
Cheers

**Comment by daleeidd** [comment] 2020-04-19 05:34
@huwb Should we discuss underwater reflections here too?

**Comment by huwb** [comment] 2020-04-19 08:01
@ftejada17 you need to set the texture sampler type to "normals".

Reflection probe will have show reflection behind the red cube (it doesn't know what's behind anything) so that's why the red cube reflection shows up behind it.

@daleeidd there's a lot going on in this thread already so I'd probably vote for specialising this to above water and creating a new one for below water. But you can also add here.

**Comment by ftejada17** [comment] 2020-04-22 15:47
Excuse the delay @huwb !
"you need to set the texture sampler type to "normals"
Thanks for telling me this detail since I did not see it.

Excuse me but I don't know what exactly you are referring to with this: "Reflection probe will have show reflection behind the red cube (it doesn't know what's behind anything) so that's why the red cube reflection shows up behind it"

@huwb said: "Its quite fiddly to get right but it seems to be promising at least. It still creates odd patches but at least they're not light brown!"

Well I think it is very promising and frankly in principle I am very happy with those results. The results are quite appreciable.
I don't know if this is what you're doing in that code, but what if we couldn't change the color of those spots from the Inspector like any other parameter? It would be another option apart from Ramp down occlusion based on reflection direction.
It would be nice to have both options if possible at the same time.

Let me know if the idea works for you ... Regards

**Comment by VizzzU** [comment] 2020-04-24 08:58
In my opinion reflection ther are some issues wich comes from the normals & little waves . I have "not bad " results with params listed in the pic joined .

![ReflectionsHDRP](https://user-images.githubusercontent.com/45937523/80194354-8eb94680-861a-11ea-916d-7bc2e443e147.jpg)

**Comment by ftejada17** [comment] 2020-04-27 12:21
These errors that @VizzzU comment, I have also observed but I did not want to dirty this thread any more. Although from the preliminary tests I have done it seems more of a problem of how Unity interprets reflections on a surface with NormalMap...
But the problem this thread was opened for hides the problem of the reflections given by the NormalMap very much. So until Hub implements the solution to this thread's problem, we won't know how much it hurts.


@huwb maybe we should open a new thread to expose this problem of reflections given by the NormalMap? And although I think this problem comes from Unity, but it could serve to raise what solutions could be made to improve this feature ... such as making reflections handled by Crest instead of letting Unity manage them. Although I don't know if this could be possible given the approach that Crest HDRP has ...

I would like to know what @huwb thinks about this matter.

**Comment by huwb** [comment] 2020-05-06 19:34
There's a lot going on in this thread and its making this hard to understand and track, and will make it difficult to find this conversation in the future. I think making new issues - one per issue - would be useful please.

@ftejada17 we don't have plans to do our own reflection - it would likely mean copying in and modifying a lot of HDRP rendering code and then maintaining it, which is not possible with our resources. we need to work with hdrp on this one.

@VizzzU yes there is a touch of waves that wont go away, its an issue with the slider ranges actually! i've been thinking about fixing this. if you want this fixed a new issue would be useful.

I will close this issue on the next release, which fixes the original issue.

**Comment by daleeidd** [comment] 2020-06-13 05:37
> I will close this issue on the next release, which fixes the original issue.

@huwb I'll close this since 4.2 is out. Reopen if this is incorrect (I saw 4.3 mentioned somewhere above)

**Closed by daleeidd** 2020-06-13 05:37 UTC
Labels: HDRP, bug
