### ISSUE TITLE
Anti aliasing bug

### ISSUE THREAD

**Issue by fikoljuky** [crest-ocean/crest#608] opened 2020-08-07 06:41 UTC
**Describe the bug**
When using any other type of AA than FXAA there are artefacts at the edges of objects while underwater. 
You can see them on the edges of the plants in the picture as these yellowish borders. 
![Foliage](https://user-images.githubusercontent.com/29865680/89616845-5e27b080-d889-11ea-8410-920e61b7e5e0.png)

I'm running unity 2019.4.5 LTS with HDRP on a windows 10 PC. 

As for my GPU model it's a 1060 GTX desktop version.

**Comment by daleeidd** [comment] 2020-08-09 14:01
Thanks for reporting. Is MSAA also enabled? And does it happen to anything else? Something to check is an object without transparency like a rock.

**Comment by OkoGoran** [comment] 2020-08-18 09:38
looks similar to this one: https://github.com/crest-ocean/crest/issues/529

**Comment by OkoGoran** [comment] 2020-12-02 16:32
Any news on this issue? We actually do now also experience this with HDRP and as described by @fikoljuky, it doesn't happen with no anti aliasing or with FXAA. It also happens if Lit Shader Mode in the HDRP Settings is on Both and with MSAA enabled.  
Untiy 2019.4.14f1 & Crest 4.6 HDRP

**Comment by daleeidd** [comment] 2020-12-02 17:34
@OkoGoran @fikoljuky I am having a hard time reproducing this. Does it happen for every material? I am guessing these are opaque with alpha clipping? Have either of you tried toggling the underwater effect to see that it is the cause? I was able to sort of reproduce but it occurred with or without the underwater effect.

**Comment by daleeidd** [comment] 2020-12-02 18:26
@OkoGoran @fikoljuky Can you try replacing _MainTex with _InputTexture in the following and letting me know if it solves it:
_Crest/Crest/Shaders/Resources/UnderwaterPostProcessHDRP.shader_

**Comment by OkoGoran** [comment] 2020-12-03 09:05
> @OkoGoran @fikoljuky Can you try replacing all instances of _MainTex with _InputTexture in the following and letting me know if it solves it:
> _Crest/Crest/Shaders/Resources/UnderwaterPostProcessHDRP.shader_

Tried this and it got quite dark below the surface and I could only see silhouettes when I turned down the fog density in the ocean shader. But no white AA artefacts. Weird thing: if I get up to the surface with the camera, everything turns black.. ? 
![ocean-test](https://user-images.githubusercontent.com/58563011/100987528-ee7fb480-354e-11eb-93f0-4a9e5c080421.gif)

**Comment by daleeidd** [comment] 2020-12-03 19:45
@OkoGoran Thanks. Which version of HDRP?

**Comment by OkoGoran** [comment] 2020-12-03 19:50
@daleeidd HDRP 7.5.1, Crest 4.6, Unity 2019.4.14f1

**Comment by daleeidd** [comment] 2020-12-04 17:11
@OkoGoran Thanks. I upgrade to HDRP 7.5.1. I was only able to reproduce the new issue for one play mode session when switching to forward from deferred. It looks like the _InputTexture wasn't being bound. But now I can switch between forward, deferred, MSAA and SMAA without issue. Are you able to try again?

I was also able to reproduce consistently by enabled _Stop NANs_ on the camera. Is this the same for you?

**Comment by daleeidd** [comment] 2020-12-08 02:41
This will be fixed for 4.7. But it requires HDRP 10. Unity has added an extra injection point before TAA/SMAA. It will require a manual change in the _custom post process ordering_ of the _HDRP pipeline asset_ since we cannot script it.

**Comment by OkoGoran** [comment] 2020-12-08 07:10
Thanks for elaborating this @daleeidd! Unfortunately I don't think we will be able to switch to Unity 2020 and therefore not to HDRP 10. Since we work with deferred rendering MSAA is not an option. Might there be another work-around for HDRP 7.5.1?

**Comment by daleeidd** [comment] 2020-12-08 19:31
Converting the post-processing effect to a custom pass is the only other decent option. It shouldn't be too difficult to do but I am not sure if that is the path we should take for Crest.

**Comment by daleeidd** [comment] 2020-12-14 21:27
I'll close this issue for now since 4.7 is out. It is also pinned. For anyone seeing this, upgrading to HDRP 10 and then changing the custom post-process ordering so that the underwater effect is rendered before TAA is the solution. As for those stuck on earlier versions of HDRP, it is uncertain as to whether we will fix this. It would require moving the underwater effect to a custom pass. It isn't certain whether that would be ideal for the underwater effect in the long run hence the hesitation. But if we do, I will update this issue.

**Closed by daleeidd** 2020-12-14 21:27 UTC
Labels: HDRP, bug, underwater

**Comment by OkoGoran** [comment] 2020-12-15 09:35
Thanks @daleeidd. Yeah we hope 2020.2 (required for HDRP 10) will soon get out of beta and that consoles will provide editor add-ons for it quite quickly. Thanks for your help!

**Comment by metromeo** [comment] 2021-04-07 12:47
I still do not fully understand, does the crest ocean work with msaa? I have this
![1](https://user-images.githubusercontent.com/5053538/113868424-558cce80-97b8-11eb-81df-a774bcf31a8a.png)

Hdrp 10.3.2
Crest 4.9

This weird thing on shroud gone, when i'm turn off msaa. With TAA, FXAA, SMAA its ok too

**Comment by daleeidd** [comment] 2021-04-07 18:15
@metromeo it's not clear what the issue is sorry. Can you provide annotations on the image and/or comparison with SMAA?

**Comment by metromeo** [comment] 2021-04-07 18:49
@daleeidd, i hope this gif can help to understand
https://gfycat.com/damagedpinkladybug
underwater pp before taa is set in hdrp defaults

**Comment by daleeidd** [comment] 2021-04-07 19:54
@metromeo Thanks. That helps a lot. Could you open a new issue? We'll see if we can get this solved.

**Comment by metromeo** [comment] 2021-04-07 20:08
Sure, thanks
