### ISSUE TITLE
[HDRP] Horizon line issue

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#456] opened 2020-03-31 12:12 UTC
**Describe the bug**
Sometimes a visible line appears at the horizon.

In the screenshot below there is a horizon line both above and below water. We may find these are two separate issues and break them out accordingly.

**Screenshots / video**
![image](https://user-images.githubusercontent.com/939901/78024916-0fa15d00-7351-11ea-87ab-1d7daab9c19b.png)

**Versions**
2019.3 HDRP

**To Reproduce**
*How can the developers reproduce this bug? Are you able to reproduce the issue in the example content/scenes?
Please include steps to reproduce the behaviour, with the example content ideally so we can follow the steps on our side.*

**Platform**
*Editor or standalone? Platform (win/mac/...)*

**Hardware**
*What hardware are you seeing the issue on? GPU model is particularly useful.*

**Additional context**
*Add any other context about the problem here.*

**Comment by daleeidd** [comment] 2020-04-02 06:20
It is very difficult to reproduce in the main scene with the provide ocean renderer settings. But if you reduce the quality (like reducing the LOD resolution to 256) it is much easier. So this could be a seam where the tiles end?

**Comment by daleeidd** [comment] 2020-04-02 06:52
![Screenshot (138)](https://user-images.githubusercontent.com/5249806/78218820-24752080-750a-11ea-8b9c-0f4f16044317.jpg)
Game View

![Screenshot (137)](https://user-images.githubusercontent.com/5249806/78218826-25a64d80-750a-11ea-969d-40d587aaed70.jpg)
Scene View

I set the LOD to 256. That is also the default value. But the main scene is set to 384.

**Comment by huwb** [comment] 2020-04-02 21:32
Oh so there are legit cracks in the water surface?? Ok.

I've had it on projects that precision errors generate cracks like this. Sometimes just scaling the tiles by 0.5% more effectively covers this stuff. However i think id like to take a closer look at hte above is it could be abug, or something that could be improved in the vert shader.

**Comment by skaughtx0r** [comment] 2020-04-03 17:31
This bug is not limited to HDRP, I've been noticing this in the Standard pipeline version as well. One of my game's users said the turning off MSAA fixed it...

**Comment by moosichu** [comment] 2020-04-04 09:19
Isn't this caused by the underwater post-process effect? It was one of the reasons why it hadn't been merged-in for BIRP, but we had never seen it in HDRP ourselves.

**Comment by skaughtx0r** [comment] 2020-04-04 15:48
Oh, yeah, I'm using the underwater post-process branch, so that is likely the issue I'm seeing.

**Comment by banan5555** [comment] 2020-04-06 09:05
Hi, I've made a short video to show that the LOD scale on my scene is similar to that from demo scenes, and the problem seems to occur due to lack of some of the tiles. From the underwater, the horizon changes from blue to transparent.
[https://youtu.be/VFyJtQRVQWg](url)

**Comment by daleeidd** [comment] 2020-04-22 12:52
@huwb I have created [test/lod-chunk-gaps](https://github.com/crest-ocean/crest/tree/test/lod-chunk-gaps) which positions the camera to show the gap. I set the LOD resolution to 256 since it is easier to reproduce that way. I found that increasing the chunk size by 0.1 covered the gap.

![Gap](https://user-images.githubusercontent.com/5249806/79983878-b78eee00-84eb-11ea-9eec-d419b06dfff5.jpg)

Just use the scene camera to view the gap up close.

**Comment by daleeidd** [comment] 2020-04-22 14:02
@banan5555 Thanks. Do you still see the thin horizon line if you set the _Geometry Down Sample Factor_ to 1?

**Comment by banan5555** [comment] 2020-04-22 15:07
@daleeidd Yes, with Geometry Down Sample Factor set to 1 still have this line:
![crest-horizonline-issue3](https://user-images.githubusercontent.com/63231118/79998484-0b351380-84bb-11ea-9143-8feca5f330df.png)
![crest-horizonline-issue4](https://user-images.githubusercontent.com/63231118/79998495-0cfed700-84bb-11ea-98e9-3934540c243f.png)

**Comment by daleeidd** [comment] 2020-04-22 15:19
@banan5555 Thank you. One last thing hopefully. Would it be possible for you to take the scene view camera over to where the line is? If it is a similar issue to what I have found then it shouldn't be too far away (maybe a 100 metres).

**Comment by banan5555** [comment] 2020-04-22 15:41
There is no gap in place where last 2 tiles are connected:
![image](https://user-images.githubusercontent.com/63231118/80002134-8f899580-84bf-11ea-9f5b-42c1f6d948f5.png)
But after that I realized that scene camera don't use 'Crest.UnderwaterPostProcessHDRP' so i disabled it in HDRP settings and now line is gone. So this issue is related to underwater post process istead of tile geometry.

**Comment by daleeidd** [comment] 2020-04-22 15:52
Thanks for doing that. It might be a different issue then. The one I can reproduce is a gap in the tiles as per the images I uploaded. The gap itself isn't caused by the underwater effect, but rather the underwater just makes it more visible since it relies on the tiles having no gap. It should be visible from the scene view if the scene view is taken to where the camera is looking and the line issue is visible in the game view camera.

**Comment by daleeidd** [comment] 2020-04-22 17:43
@banan5555 what value is your far clip plane? Does increasing it make a difference?

**Comment by banan5555** [comment] 2020-04-22 18:36
@daleeidd far clip plane 6000k, but i check right now with different values and issue was on all of them. In one of tests I notice that line is moving:
https://youtu.be/Hzxku50E5wg

With different far clip plane values it shows with different rotations, with near clip plane set to 1 it is very hard to reproduce but this value is unacceptable for us. I made video maybe you will find anything here:
https://youtu.be/7yHGE_-9ra8

**Comment by daleeidd** [comment] 2020-04-22 19:08
Thank you. I appreciate your assistance.

**Comment by banan5555** [comment] 2020-04-22 20:05
I attached RenderDoc snapshot in different thread:
https://github.com/crest-ocean/crest/issues/479#issuecomment-617977350

**Comment by moosichu** [comment] 2020-04-25 12:44
PR #484 should help with this as well.

**Comment by huwb** [comment] 2020-05-16 08:53
Hi all, it seems like at least some horizon line issues are related to the ocean not covering the extents of the camera frustum which is currently a requirement.

If you are seeing a horizontal line above/below water at the horizon could you try experimenting with the far clip plane of the camera - does reducing it help?

If it does then this is one solution, and an alternative solution is to increase the area covered by the ocean which we can discuss.

**Comment by banan5555** [comment] 2020-05-16 11:06
> @daleeidd far clip plane 6000, but i check right now with different values and issue was on all of them. In one of tests I notice that line is moving:
> https://youtu.be/Hzxku50E5wg
> 
> With different far clip plane values it shows with different rotations, with near clip plane set to 1 it is very hard to reproduce but this value is unacceptable for us. I made video maybe you will find anything here:
> https://youtu.be/7yHGE_-9ra8

Hi, far clip plane does not reducing it as I comment 24 days ago. In second video you can see that I test 10000 far clip plane and it not fix issue.

**Comment by huwb** [comment] 2020-05-16 11:10
Ah fair thanks. After i posted the above that Tom also noted the same, apologies for the noise here. Tom has a fix of this that we're reviewing/testing for the next release.

**Comment by moosichu** [comment] 2020-05-16 12:50
PR #402 has been merged and has also been ported to HDRP so should be available soon, will close this issue when the HDRP release with this fix has landed.

**Comment by moosichu** [comment] 2020-05-23 17:44
This should be fixed it the latest HDRP release (although #479 still happens).

**Closed by moosichu** 2020-05-23 17:44 UTC
Labels: HDRP, bug
