### ISSUE TITLE
Waves "ShapeGerstnerBatched with Gerstner Batch Geometry" don't work in a Build

### ISSUE THREAD

**Issue by ftejada17** [crest-ocean/crest#557] opened 2020-06-20 13:07 UTC
Hi!!! 
I'm having a problem ... Unity 2019.4.0f1, HDRP 7.3.1, Crest 4.2 (although I think it will also happen with 4.3, I haven't had time to update yet).
**I have several planes in the scene with the component "ShapeGerstnerBatched" and the material "Gerstner Batch Geometry"** to simulate coast waves
Everything works perfectly in Editor:
https://youtu.be/t867fg_8hP0

But in a build (to Windows) there are not those waves and it seems that it throws nulls.
Before migrating my project to Unity 2019.4.0f1, I made a build with 2019.3.x and the problem did not pass ... (Maybe this gives you a clue or maybe it is just coincidence).

Cheers

**Comment by daleeidd** [comment] 2020-06-20 13:14
Thanks. How many _ShapeGerstnerBatched_ do you have?

**Comment by ftejada17** [comment] 2020-06-22 00:46
3 + the main it has for the entire ocean

**Comment by daleeidd** [comment] 2020-06-26 01:56
That's not that many. I tried this on Windows with 4.2 and couldn't reproduce. Has the shader, material and mesh made it over to the build?

> and it seems that it throws nulls

Does it produce any logs?

**Comment by ftejada17** [comment] 2020-06-26 18:10
> 
> 
> That's not that many. I tried this on Windows with 4.2 and couldn't reproduce. Has the shader, material and mesh made it over to the build?
> 
> > and it seems that it throws nulls
> 
> Anything in the logs?

@daleeidd  If you mean the 3 planes in the scene with the component "ShapeGerstnerBatched" , the material "Gerstner Batch Geometry" and shader, I don't know. I don't know how to look at that.
What I can tell you is the ocean renders well in the build with the waves from the main input. But the waves of "3 planes" are not shown and by console in the build it throws a null every frames.
When I make the build of the same scene but deactivating the Inputs of "3 planes" the null by console in the build does not appear ... so 2 + 2 I imagine that it is 4.

Do you know where the build log is stored to send it to you? Regards

**Comment by daleeidd** [comment] 2020-06-26 18:30
Oh... can you paste the null exception you see in the console here?

**Comment by ftejada17** [comment] 2020-06-26 18:35
> 
> 
> Oh... can you paste the null exception you see in the console here?

@daleeidd  I'm out but I'm going to try to put a video on you if I find it. If not, when I get to the office in a few days I will make a new build and record a video for you to see

**Comment by ftejada17** [comment] 2020-06-26 18:56
@daleeidd See if this works for you:
https://youtu.be/SL_ITEO60K0

**Comment by daleeidd** [comment] 2020-06-27 04:52
It looks like the power log and power disabled arrays don't have matching lengths. I don't know how it would get in that state by itself. I could just add a guard against this, but I would like to know the cause to ensure it isn't something worse.

There is a function which is only called in the editor which might be the reason it only works there. But I don't think it is the issue since it works fine in normal circumstances. 

It may be possible that your spectrum is corrupted. Are you using the same wave spectrum asset for all gerstner components? Can you inspect the spectrum asset without the inspector throwing exceptions?

How are you instantiating these components? Are they saved in the scene as normal or are they created with scripting?

> when I get to the office in a few days

No worries. Take your time.

**Comment by huwb** [comment] 2020-06-27 05:42
Interesting.. one additional thought - there is an option whether this data is generated at runtime or just used off the component. Is this option enabled: Evaluate Spectrum At Runtime

We could probably add validation to check array lengths for this case.

**Comment by ftejada17** [comment] 2020-06-27 20:18
" @daleeidd said: There is a function which is only called in the editor which might be the reason it only works there. But I don't think it is the issue since it works fine in normal circumstances."
I don't think this is because the first build I did with the version of Crest 4.1 the problem did not happen ... (unless in step 4.1 to 4.2 you have changed that).

" @daleeidd said: It may be possible that your spectrum is corrupted. Are you using the same wave spectrum asset for all gerstner components? Can you inspect the spectrum asset without the inspector throwing exceptions?"
It may be that since I had them created from version 4.1 and I saved them in another folder to keep them when I updated to 4.2.
And updating one of the 3 spectra gave very strange results that were not the same as the ones it had in the previous version.

So I'm going to delete those 3 spectrum and create new ones to see if it solves the problem.

" @daleeidd said: How are you instantiating these components? Are they saved in the scene as normal or are they created with scripting?"
They are stored on the scene as normal. I don't create them by script.

As soon as I can I will try it and tell you ...

" @huwb said: Interesting .. one additional thought - there is an option whether this data is generated at runtime or just used off the component. Is this option enabled: Evaluate Spectrum At Runtime"
I'm going to look at where this option is to verify how it is ...

Regards

**Comment by daleeidd** [comment] 2020-06-28 03:20
> (unless in step 4.1 to 4.2 you have changed that)

I had a look at the source changes for both the gerstner and spectrum components and nothing relative to this issue has changed.

> As soon as I can I will try it and tell you ...

No worries. Looking forward to what you find.

**Comment by ftejada17** [comment] 2020-06-28 09:58
"@huwb said: Interesting .. one additional thought - there is an option whether this data is generated at runtime or just used off the component. Is this option enabled: Evaluate Spectrum At Runtime"

**I have checked and was enabled on all three.**

@daleeidd and @huwb On the other hand I have created a new "spectrum", I have dragged it to the three "ShapeGerstnerBatched" and I have made a new buid ... but the problem keeps happening ... Although now the nulls by console do not appear in the build .. . It's very strange...

Can it influence the values that a spectrum waves may have, for example some very high values in some ranges? I say this because the general Spectrum that the ocean has also had it saved from the previous version of Crest when I updated ... and this does not give problems ...
The problem seems to be happening when using a spectrumWaves with "the component" ShapeGerstnerBatched "and the material" Gerstner Batch Geometry ""
Does it make any sense to you?
or, Could it be something related to the Shader "Gerstner Batch Geometry" and the nulls of waveSpectrum was just a coincidence ...?

**Comment by fi4sk0** [comment] 2020-06-30 06:42
I tried to investigate a bit and found out, having the corresponding .asset file open in Visual Studio Code, that clicking on "Phillips" and changing the wind speed does affect the sliders above in the editor, but the values do not get saved to the .asset file. 

When I disable the "Phillips" button by clicking it again and I move one of the spectrum sliders, the values get saved to the .asset file. Doing this also makes it work in the build. 

There might be an issue regarding the use of Undo.RecordObject in 
https://github.com/crest-ocean/crest/blob/46195e4c129ab01495942ad61e3eecd77e71f2cc/crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs#L441 
and others. Seems like this is called every frame that the inspector is drawn and "Phillips"-Button is toggled on. In the example for RecordObject, a change check is done before calling RecordObject. Maybe that might be a cause?
https://docs.unity3d.com/ScriptReference/Undo.RecordObject.html  

I'm using Unity Editor 2020.2.0a15 on macOS 10.15.5

**Comment by daleeidd** [comment] 2020-07-02 12:18
@fi4sk0 Thanks. That appears to be the separate issue. Too early to say. Calling it every frame might be ok, but the undo/redo history does appear broken. The toggle state style of the button being broken is another issue too I noticed.

@ftejada17 Could you send me your spectrum asset file on discord?

**Comment by daleeidd** [comment] 2020-07-13 13:39
So this was an empty value in the asset file for the _powerDisabled array. In the editor it would bypass the serialised asset value to initialise this array with the correct length using the custom inspector. But in a build it would read the empty value and deserialise it as an empty array. We had no checks so an exception was thrown as stated above.

As for how the spectrum asset file came into this state in the first place, I don't know. But apparently is was caused by an upgrade of Crest.

I'll add checks for this and I am rewriting the spectrum inspector to fix issues with undo/redo and state not saving correctly. Will do a PR tomorrow.

**Comment by daleeidd** [comment] 2020-07-14 02:53
@ftejada17 Thank you for reporting and working with me on discord to resolving this. In 4.5 we will guard against this issue and provide feedback with d4619a5. A user can fix outdated or invalid spectrums by saving the broken spectrum (might need to make a change first). This can be done without 4.5.

@fi4sk0 Thanks for reporting the inspector issue. #586 improves the spectrum inspector to behave more intuitively by serialising all properties which makes it work correctly with undo/redo.

I'll close this once 4.5 is released.

**Comment by daleeidd** [comment] 2020-08-17 16:02
4.5 is released which solves this issue.

**Closed by daleeidd** 2020-08-17 16:02 UTC
Labels: bug
