### ISSUE TITLE
Waves not forming properly, LOD and other strangeness

### ISSUE THREAD

**Issue by Draydak** [crest-ocean/crest#279] opened 2019-06-29 15:27 UTC
**Describe the bug**
Fresh download of Crest (29th June 2019) from Git. Open in Unity, open any demo scene and the waves are all Muted / flat. The Whirlpool scene was craziest, see video. There does not appear to be any wake / bow wake on any boats. But it could just be so shallow, it's not visible.

LOD appears to be behaving oddly, also only appearing in bottom image slot (again see video)

**Screenshots / video**
[Crest Issue](https://youtu.be/_DSPuQbSBBc)

![image](https://user-images.githubusercontent.com/939901/63832846-8b759a00-c969-11e9-9bcd-832046d7b234.png)

**Log**
No error's / problems in Log at all.

**Versions**
Git version, master branch downloaded (29th June).
Unity 2018.4.2f1

**To Reproduce**
Download from Git master branch to empty folder.
Open in Unity, open any demo scene.
**No** changes, **no** modifications, **not** added to existing project etc.

**Platform**
Editor and standalone
Windows 10
Nvidia Geforce GT 650M

**Additional context**
I believe the graphics card is fully DX11 compatible, so should be capable of handling required shaders. (it worked with earlier versions).
All drivers are up-to-date.

**Comment by moosichu** [comment] 2019-06-30 05:31
Hi @Draydak,

A few things which could help us debug this issue:
- Could you please enable the debug view of all the other LodMgrs and send a screenshot of that (tick the boxes on the bottom of the game screen).
- Could you please add ` #pragma enable_d3d11_debug_symbols` to line 27 in `AnimWavesGerstnerBatches`
- Could you please [capture, save and upload](https://docs.unity3d.com/Manual/RenderDocIntegration.html) a renderdoc capture so we can try and debug the issue.

Doing the first one should be fairly easy, so do that first. If you can take the time to do this it would really help because we are unable to recreate the bug on our end!

**Comment by moosichu** [comment] 2019-06-30 07:33
Oh, another quick thing that you could do is a take a screenshot of what things look like when you uncheck `Shape combine pass` in the overlay on the left.

**Comment by Draydak** [comment] 2019-06-30 08:03
![image](https://user-images.githubusercontent.com/39652045/60394039-3ad6f180-9b1e-11e9-85f3-93629e8365e0.png)

**Comment by Draydak** [comment] 2019-06-30 08:08
Unchecked shape combine pass, this made big difference
![image](https://user-images.githubusercontent.com/39652045/60394093-fac43e80-9b1e-11e9-8986-1b06e478a6f4.png)

**Comment by moosichu** [comment] 2019-06-30 08:16
Awesome, the renderdoc capture would really help here (with shape combine pass activated so that bug itself is captured). I know which shader the bug is happening in, because I was able to replicate it on Linux, but a DX11 capture with debug symbols would really help as well.

**Comment by Draydak** [comment] 2019-06-30 08:28
I need to download Renderdoc etc. (not something I've used)
But work is dragging me a way for a bit so might not get that capture to you till later

**Comment by moosichu** [comment] 2019-06-30 08:41
No worries, will let you know if I find the culprit beforehand

**Comment by Draydak** [comment] 2019-06-30 08:47
Had a quick go, not sure if this is right as just followed my instincts.

[CrestIssue279.zip](https://github.com/huwb/crest-oceanrender/files/3342686/CrestIssue279.zip)

If you need me to toggle something more in RenderDoc / Unity that I've missed let me know

**Comment by moosichu** [comment] 2019-06-30 08:59
Thanks. The capture itself looks fine, but it seems like you paused the game window before you made it which means that it doesn't contain a capture of the bugged behaviour. If possible please do the same again but whilst the game is running.

(If this isn't what happened, let me know and I will see if I can work out why the relevant info is missing from the capture).

**Comment by huwb** [comment] 2019-06-30 09:18
Render doc will replay the capture on whatever device / os you're running. Maybe you can capture and run rd on your Linux setup?

**Comment by moosichu** [comment] 2019-06-30 10:22
Another option could be to update your drivers (but send through capture first).

**Comment by moosichu** [comment] 2019-06-30 10:24
The Linux issue appeared to be something else, as it went away after I restarted my PC. :/

**Comment by Draydak** [comment] 2019-06-30 14:09
[CrestIssue279.zip](https://github.com/huwb/crest-oceanrender/files/3342958/CrestIssue279.zip)

Second attempt, triggered from inside Unity (aka read manual page more). At a glance some crest Lod data in there, but it's all voodoo to me. I'm not familiar with RenderDoc so feel free to spell out any specifics I need to do.

**Comment by moosichu** [comment] 2019-06-30 15:52
That renderdoc capture is exactly what we were after and has already revealed some useful info.

I'm going to dig through it some more, but for some reason renderdoc is reporting that none of the animated wave shaders *ever* get run. Normally you get this if the kernel cannot be found or something similar, but that would *spam* errors to the log. I'm going to do some thinking and see if there is something we can do on our end to verify things.

**Comment by moosichu** [comment] 2019-07-18 20:27
https://drive.google.com/file/d/1A8A76u96RJDnUo5Yuim6Wm3fk3630Qns/view?usp=sharing

Can you give this a go and tell me what results you get?

**Comment by Draydak** [comment] 2019-07-19 06:46
![image](https://user-images.githubusercontent.com/39652045/61514812-3442e800-aa01-11e9-94f7-ab1361d420a5.png)

Still seems to have same issue, the few errors mainly relate to PostProcessing from looks.

`Initialize engine version: 2018.4.2f1 (d6fb3630ea75)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GT 650M (ID=0xfd1)
    Vendor:   
    VRAM:     2007 MB
    Driver:   25.21.14.2531
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script (UnityEngine.Rendering.PostProcessing.PostProcessResources) on this Behaviour is missing!
 
(Filename: C:\buildslave\unity\build\Runtime/Scripting/ManagedReference/SerializableManagedRef.cpp Line: 195)

The referenced script on this Behaviour (Game Object '<null>') is missing!
 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 294)

A scripted object (probably UnityEngine.Rendering.PostProcessing.PostProcessResources?) has a different serialization layout when loading. (Read 52 bytes but expected 1356 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
0x00007FFFC926400C (UnityPlayer) 
0x00007FFFC9267339 (UnityPlayer) 
0x00007FFFC924DEBC (UnityPlayer) 
0x00007FFFC9F73EC7 (UnityPlayer) UnityMain
0x00007FFFC9AE26AA (UnityPlayer) UnityMain
0x00007FFFC9AE4550 (UnityPlayer) UnityMain
0x00007FFFC9AE3C55 (UnityPlayer) UnityMain
0x00007FFFC9AE12FB (UnityPlayer) UnityMain
0x00007FFFC982B9BA (UnityPlayer) UnityMain
0x00007FFFC982C5B3 (UnityPlayer) UnityMain
0x00007FFFC982C9AD (UnityPlayer) UnityMain
0x00007FFFC98E59EF (UnityPlayer) UnityMain
0x00007FF83D907974 (KERNEL32) BaseThreadInitThunk
0x00007FF8403DA271 (ntdll) RtlUserThreadStart
 
(Filename: C:\buildslave\unity\build\Runtime/Serialize/SerializedFile.cpp Line: 2001)

The referenced script (UnityEngine.Rendering.PostProcessing.PostProcessLayer) on this Behaviour is missing!
 
(Filename: C:\buildslave\unity\build\Runtime/Scripting/ManagedReference/SerializableManagedRef.cpp Line: 195)

The referenced script on this Behaviour (Game Object 'Main Camera') is missing!
 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 294)

A scripted object (probably UnityEngine.Rendering.PostProcessing.PostProcessLayer?) has a different serialization layout when loading. (Read 32 bytes but expected 188 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
0x00007FFFC926400C (UnityPlayer) 
0x00007FFFC9267339 (UnityPlayer) 
0x00007FFFC924DEBC (UnityPlayer) 
0x00007FFFC9F73EC7 (UnityPlayer) UnityMain
0x00007FFFC9AE26AA (UnityPlayer) UnityMain
0x00007FFFC9AE4550 (UnityPlayer) UnityMain
0x00007FFFC9AE3C55 (UnityPlayer) UnityMain
0x00007FFFC9AE12FB (UnityPlayer) UnityMain
0x00007FFFC982BA94 (UnityPlayer) UnityMain
0x00007FFFC982C5B3 (UnityPlayer) UnityMain
0x00007FFFC982C9AD (UnityPlayer) UnityMain
0x00007FFFC98E59EF (UnityPlayer) UnityMain
0x00007FF83D907974 (KERNEL32) BaseThreadInitThunk
0x00007FF8403DA271 (ntdll) RtlUserThreadStart
 
(Filename: C:\buildslave\unity\build\Runtime/Serialize/SerializedFile.cpp Line: 2001)

UnloadTime: 7.451700 ms`

**Comment by huwb** [comment] 2019-08-07 20:28
Likely connected to #301

**Comment by huwb** [comment] 2019-08-07 20:52
@Draydak  we now have 3 cases of this bug occurring for users.

This is probably a long shot but i noticed above you said it was working for you on earlier versions. You don't happen to know a version/date that was working? It might allow us to compare the versions and give us leads..

**Comment by Draydak** [comment] 2019-08-08 07:19
Version 7.0.0 definitely works ok for me, downloaded just other day as water is now under the microscope in my project. 

I believe it was good until April / May time, but my Git skills are not good enough to confirm.

**Comment by huwb** [comment] 2019-08-08 19:07
@Draydak if you have time could you please run this build, and attach a screenshot of what you get? This is taken just before we did a major upgrade to the core crest update - added compute shaders.

https://drive.google.com/open?id=1-UgFF60DSGRyqa5T3U3IYLb1vl4O-OIa

**Comment by huwb** [comment] 2019-08-08 19:46
@Draydak after much headscratching we may have ID'd the issue. could you please give this new build a test when you get a chance and let us know if it resolves the issue? (if it does, disregard the previous request above)

https://drive.google.com/open?id=1OBC2MXWC2KerxkKtujekMctnvHsUVSj3

thanks!

**Comment by Draydak** [comment] 2019-08-09 11:08
Last one first "the fix"
![image](https://user-images.githubusercontent.com/39652045/62774964-ad84a680-baa6-11e9-9563-4eea87a0a2df.png)
Still no good I'm afraid

**Comment by Draydak** [comment] 2019-08-09 11:13
The Crest-28ebf08b
![image](https://user-images.githubusercontent.com/39652045/62775197-487d8080-baa7-11e9-8912-99416c607150.png)

This does work, if that is any help to you.

**Comment by moosichu** [comment] 2019-08-17 14:29
Thanks a lot for your patience with this. How does this build fair for you? This is a build made from #316, shadows and foam are broken but waves do work.

https://drive.google.com/file/d/19VYoMT43OQ97ZLrDnkIZBYQkNux4WsaV/view?usp=sharing

**Comment by moosichu** [comment] 2019-08-17 14:55
Here's another build, it's deliberately broken, but you should get results like this:

![image](https://user-images.githubusercontent.com/10348641/63213681-30d97400-c107-11e9-8b9f-5236a461fce5.png)

https://drive.google.com/open?id=1YsS5eRyKZxOWKpSk2NIxak8XlMSYrc4B

Just trying to throw different things at the wall to see what sticks.

**Comment by Draydak** [comment] 2019-08-17 15:34
the build from 316 looks as follows, sadly not working

![image](https://user-images.githubusercontent.com/39652045/63214178-33db6100-c115-11e9-8d6f-fa2f6c709d1b.png)

**Comment by Draydak** [comment] 2019-08-17 15:36
the simple array copy build:

![image](https://user-images.githubusercontent.com/39652045/63214204-874daf00-c115-11e9-97f7-8bea8eaaa33f.png)

**Comment by moosichu** [comment] 2019-08-18 19:28
Two builds incoming, they should both look like this (foam, etc. will be broken, but waves should work):

![image](https://user-images.githubusercontent.com/10348641/63229139-2a292a80-c1f5-11e9-8775-f19774aba2de.png)

One of these builds has reverted back to using the pixel shader (which is what already works for you), so if that doesn't work we are then in interesting territory.

# Build 1

https://drive.google.com/open?id=1szwYoCRGxEV4CSqKWMNIALYvbBMFG1R5

# Build 2

https://drive.google.com/open?id=1-gu2QictZuxD4fWwJbajSzPcKJ3_Sz6l

**Comment by Draydak** [comment] 2019-08-19 09:41
Build 1:
![image](https://user-images.githubusercontent.com/39652045/63255236-98153680-c275-11e9-9c35-398cf9024449.png)

Build 2:
![image](https://user-images.githubusercontent.com/39652045/63255369-eaeeee00-c275-11e9-80d0-5d7e6441c31a.png)

They both work!
Hope that is a good thing

**Comment by huwb** [comment] 2019-08-22 20:40
We just realised today that we think the three cases of this that we're aware of are likely all from unity 2018.

We should probably eliminate this important factor from the equation.. @Draydak if you get a chance could you please try this build i made from 2019? Thanks.. https://drive.google.com/open?id=1tKI0jlGswdKQadeyHTLjrn3XxlJD608s

**Comment by moosichu** [comment] 2019-08-22 21:09
I've hijacked the issue description to summarise our findings. The issue does seem to be due to an attempt to read a RWTexture2D (which is weird, because writing to them is fine). I'm going to setup a bunch of experiments next week in a single Unity (non-crest) project to see if we can pin-down a common denominator. Thanks so much for your patience with this @Draydak!

**Comment by Draydak** [comment] 2019-08-23 07:33
I've been trying on 2019 myself recently since I've moved my project to that in anticipation of changing it to LWRP. I tested the build anyway, but as expected does not work.

Although I'm doubtful that I will be able to use Crest in my current project and to be honest Crest is probably overkill for my current requirements. I cannot deny the performance of Crest, so it would be a shame not to use it. I can only afford to treat my project as a hobby at moment, so it moves at it's own pace.

I will try and support you guys in any way I can, it only takes a moment to test a build so it's the least I can do.

**Comment by huwb** [comment] 2019-08-28 06:57
# Technical findings so far

We still haven't pinned down the cause of the bug, but we have tried various experiments to verify what does and does not cause it.

It's worth noting that it *only* affects the *ShapeCombine* shader.

Here are a variety of configuration descriptions, alongside wether or not they presented the bug:

(🐛 means this configuration presented the bug, 🆗 means that bug wasn't present 😄 )

- 🐛 Standard Setup - Compute Shader Dispatched once to combine each LOD, previous LOD sampled using `RWTextureArray2D<float4>`, WaveBuffer sampled using `Texture2DArray` with texture sampler. 
- 🐛 Standard Setup w/o Texture Arrays - Compute Shader Dispatched once to combine each LOD, previous LOD sampled using `RWTexture2D<float4>`, WaveBuffer sampled using `Texture2D` with texture sampler. NOTE: This rules out the cause of the bug being due to reading/writing to the same texture array in the same shader pass, as now the different lods are entirely different textures.
- 🐛 Trying to copy the previous lod as-is (w/o Texture Arrays) - Compute Shader Dispatched once to combine each LOD, previous LOD sampled using `RWTextureArray2D<float4>`, WaveBuffer sampled using `Texture2DArray` with texture sampler. NOTE: This rules out the cause of the bug being due to indexing the texture array with the wrong type, as this experiment properly used uints. 
- 🆗 Standard Setup w/o Texture Arrays and RWTexture2D for previous lod - Compute Shader Dispatched once to combine each LOD, previous LOD sampled and WaveBuffer sampled using `Texture2D` with texture sampler. NOTE: This rules out the cause of the bug being due to compute shaders.
- 🆗 Old pixel-shader based setup.

It's worth noting that in the renderdoc caputure, *the shaders which were meant to dispatch don't show up as having __dispatched at all__*. https://github.com/huwb/crest-oceanrender/files/3342958/CrestIssue279.zip

**Comment by huwb** [comment] 2019-08-31 15:41
We have a new theory - it may be due to limited/patchy support for typed UAV loads. https://docs.microsoft.com/en-us/windows/win32/direct3d12/typed-unordered-access-view-loads

This build loads the wave data as a single Float32. it will look broken but waves should be visible. could i please get a test run of this with a screenshot of the result?

https://drive.google.com/open?id=1w-aOfXhubgM1aiuG_qfTN_mVcBVzq4SJ

As a side note, it may be worth trying other APIs like Vulkan for example (can be configured in the player settings), although this may be hardware limitation in the end. And this suggestion won't help the android devices.

**Comment by Draydak** [comment] 2019-08-31 16:23
There's something on the LOD
![image](https://user-images.githubusercontent.com/39652045/64066614-5e044700-cc1c-11e9-98ff-b770875ae3b6.png)

**Comment by huwb** [comment] 2019-08-31 16:44
Yep thats what i get too, so that seems to confirm the issue.

I'll discuss how we might work around this with @moosichu . Thanks @Draydak .

**Comment by wes-hawkins** [comment] 2019-09-14 17:08
Count me in on having this issue. I first imported Crest into a project on my work computer (with a GTX 1080), and the water looked perfect. I pushed the project to GitHub and headed home. When I got home I loaded it onto my home computer, which has a GTX 950 as well as a GTX 770, and was surprised to find the water was completely flat. Tried fiddling with all kinds of stuff to make sure the Gerstner shape generator was being picked up by Crest... wasn't throwing any errors, it just refuses to make waves.

Should note that I'm using the 'Digital Ruby' branch of WM, though he says he's made only 'very minor changes' in the branch that shouldn't have anything to do with this issue. I have tried pulling the up-to-date master branch of Crest and had the same results.

![waves_no_work](https://user-images.githubusercontent.com/8751797/64911506-6c9c3500-d6d7-11e9-8d66-2401780c6341.png)

**Comment by huwb** [comment] 2019-09-16 13:12
@moosichu came up with a scheme where the displacements is a single channel texture array, with contiguous sections of the array assigned to each channel:

[ x0 x1 x2 ... y0 y1 y2 ... z0 z1 z2 ... sss0 sss1 sss2 ...]

And we found a way to integrate this without too many special cases.

This build should produce waves - could we please get verifications that it works for you guys?

https://drive.google.com/open?id=12LxuKlEdZFPC6NPKnJ-l2LhMe3iwbMip


That's the good news - the less good news is that it the displacement texture readback to CPU (for collision/buoyancy) is going to be a nightmare if we're needing to transfer each channel individually, it will make a complex system even more complex, and will double the required bandwidth.

@moosichu and I will discuss. We have plans to change up how the collision buoyancy is done and not transfer the entire displacement textures from the GPU, and this future implementation should work with this workaround, so that seems to be the best option. We don't have an ETA for this but hope to start experimenting with it soon.

Before the new system arrives, displacement texture readback will not work with these workarounds, and the other options are the Null Collider which is just a flat horizontal plane, or CPU Gerstner which will evaluate the waves on the CPU. The CPU collision does not support shallow water, so is only a good fit for deep, open ocean. There is a prototype which does take the depth caches into account, it's not been cleaned up or extensively tested but might be a good option: https://drive.google.com/open?id=12LxuKlEdZFPC6NPKnJ-l2LhMe3iwbMip

**Comment by Draydak** [comment] 2019-09-16 15:53
![image](https://user-images.githubusercontent.com/39652045/64972535-c05e7800-d8a9-11e9-969e-8fdba5309c4a.png)

I see waves, sea waves... it appears functional!
for me at least, hopefully others too.

It's a shame you can't just sample an area around the object you want buoyant, instead of feeding back all the data. But hopefully you clever chaps can come up with something workable.

**Comment by moosichu** [comment] 2019-09-16 15:58
Absolute aces! Thank you for your patience and testing! 👍 This was definetely a weird issue, now that we know the solution will work, we can get this robust and polished.

**Comment by wes-hawkins** [comment] 2019-09-16 23:33
![image](https://user-images.githubusercontent.com/8751797/65000238-b33c8b80-d89f-11e9-98a8-69fff672da13.png)

Waves ahoy here as well! Very cool!

**Comment by huwb** [comment] 2019-09-17 08:53
After discussing we werent happy with the drawbacks of the above, so time for yet another pivot - we made a new version which works around the UAV issue by using normal shaders instead of compute shaders. This adds a few passes but they are simple copies and it should not hit performance. On the plus side this doesnt suffer from the above limitations and 1 or 2 more, and keeps the solution nice and simple.

This should work but could i please get a confirmation or two, again. It looks like we're on the home straight now. 

https://drive.google.com/open?id=1Hmnmyv2P1EMvUkurQIyx05jbxasGYb84

Thanks again for your patience..

**Comment by Draydak** [comment] 2019-09-17 09:12
![image](https://user-images.githubusercontent.com/39652045/65028080-bd13cc80-d93b-11e9-9890-329cb19440ad.png)

Can confirm, waves are working

**Comment by huwb** [comment] 2019-09-18 07:50
Today a miracle happened - we merged in the above fix into the master branch. Could I please get verifications that it works on the latest version? Thanks!

**Comment by huwb** [comment] 2019-09-18 08:07
Solutions

**Scrapping texture arrays**

+ Tested
+ Potentially more flexibility with dyn wave sim adaptive time steps
- Code becomes more complex and ugly
- More draw calls

More tradeoffs here: #316 

**Splitting into single channel per slice**

- Changes semantic meaning of slices in this special case - channels multiplexed into slices, for displacements only
- Require special case functions for sampling displacements
- "Wrap" addressing doesnt work in depth dimension - uv (0, 0, 6.5) might lerp completely different channels..
- We could not get packing to work (branch `fix/uav-support-2-pack-f16s`), so this doubles memory/bandwidth requirement for the displacement texture array
- Breaks displacement readbacks, although we want to overhaul this system anyway

**Ping pong wave combine**

+ Branches the combine code, rest of code/shaders/semantics remain unchanged
- One extra texture copy per LOD to do the 'pong'

**Comment by Draydak** [comment] 2019-09-18 16:10
Can confirm it is working! 😄 

**Observations**
Performance wise it does seem to have suffered, however if that's specific to this change or how much Crest has matured in last few months... I cannot say

On a positive note, the boat scenes are much more stable than I remember!
Although I did turn around at one point and see a boat falling from the sky, so it's not perfect.

I'd be interested to hear other peoples experiences, especially on how or if it's affected performance.

**Comment by moosichu** [comment] 2019-09-18 17:14
Compared to older versions of Crest, the example scenes have quadruple the resolution and more gerstner waves, which is probably where that hit comes from. Shouldn't affect projects with existing settings though.

**Comment by huwb** [comment] 2019-09-19 10:34
Yeah that's right. The lod resolution may be a bit higher, and the dynamic
wave sim does 1 or 2 more steps.

The new ping pong combine pass can be turned on/off at runtime using the
debug gui which can be used to compare perf.

**Comment by huwb** [comment] 2019-09-20 09:37
Closing!

**Closed by huwb** 2019-09-20 09:37 UTC
Labels: bug

**Comment by huwb** [comment] 2019-09-28 13:53
A new LWRP package has been submitted with this fix. It should go up in the next couple of days, I'll confirm when it does.

**Comment by huwb** [comment] 2019-09-30 07:02
The fix is now live in version 2.2 of the asset.

**Comment by daleeidd** [comment] 2019-12-17 07:44
I might be experiencing this issue. Confirmed working normal (7.0) before texture arrays. My situation is a little different though:

MacOS Catalina (Metal)
Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
I have an RX580 as an eGPU
Unity 2018.4 and 2019.2 (built-in pipeline)
Crest version 8.0 and master

When not using the eGPU (Intel iGPU), it only occurs when LOD resolution is set to 384 (default). But if I reduce it to 256 it works correctly. If I use the eGPU, this issue doesn't occur whether set to 256 or 384.

Metal isn't my target platform, so I don't need it fixed, but I thought it might be useful information. I can provide more information here or in a new issue if desired.

**Comment by huwb** [comment] 2019-12-17 08:04
Thanks. This seems like a different cause / problem. Just to confirm, theres no errors or warnings in the log? If you're up for making a new issue i think that would be useful. Thanks

**Comment by daleeidd** [comment] 2019-12-17 10:37
No errors or warnings. Can do! I'll test it on another Mac first. I suspect I might have faulty hardware. Probably not the issue here but I might as well.

**Comment by moosichu** [comment] 2019-12-27 12:19
I've created a seperate issue for the weirdness on Macs as they are unrelated to this (I think). #384 

Thanks for spotting this @daleeidd! I'm jumping back onto Crest development after a bit of a hiatus and one of the first things I noticed was that things didn't seem to work on Mac anymore.

**Comment by moosichu** [comment] 2019-12-27 12:54
We also tried chasing up the root cause if this with Unity, but they couldn't reproduce the bug and told us to try and see if we could get anyone to check it out on the forums. So might have to do that at some point.
