### ISSUE TITLE
Performance degradation enabling shadowing in LWRP on Mac OS (Targeting Mac/Windows) 

### ISSUE THREAD

**Issue by ncthbrt** [crest-ocean/crest#307] opened 2019-07-27 13:05 UTC
**Describe the bug**
Enabling shadowing in the LWRP asset, material and ocean renderer in editor, results in a framerate of between approximately 20-8 FPS on Mac OS. 

**Versions**
- Unity v2019.1.10f1
- LWRP v5.16.1
- Crest v1.8  - Jul 1 asset store release

**To Reproduce**
- Create new LWRP project on Mac OS
- Upgrade LWRP to v5.16.1
- Import Crest from asset store
- Open settings and navigation to graphics section. Set the render pipeline asset to the one found in the Crest/Crest-Examples/ 
- Open Crest/Crest-Examples/Main/main scene
- Add "Terrain" layer to user layers
- Set the game object Island0 to use the "Terrain" layer
- Enable shadowing in ocean-underwater material
- In the ocean renderer game object, select: Create Shadow Data. This should already result in a performance drop in play mode (I got <20 FPS). 
- Enabling dynamic waves and flow simulations drops this even further. 
- Disabling shadowing and performing an editor restart even with the other features enabled results in a good frame rate at 1080p (~90FPS).

**Platform**
 - Editor
 - Platform:
        - Mac OS Mojave (v10.14.5) 
        - RAM: 16 GB
        - CPU: 2,6 GHz Intel Core i7
        - Graphics: Metal, Radeon Pro 450 2 GB & Intel HD Graphics 530 1536 MB

**Comment by huwb** [comment] 2019-08-02 15:25
Thanks, i think we were able to repro this. We'll update you with any progress.

It would be interesting to see the GPU profile from unity's profiler window to see where unity is attributing the time.

**Comment by moosichu** [comment] 2019-09-05 18:29
I have a Mac now, so will be looking into this at some point soon 😄

**Comment by ncthbrt** [comment] 2019-09-05 19:18
Thanks @moosichu! I unfortunately don't anymore, (it got stolen). I apologise that I wasn't able to provide more information.

**Comment by huwb** [comment] 2020-04-05 13:07
Might be worth a retest with #464 merged in? NaNs coudl be generated without this fix which might make metal very unhappy.

**Comment by huwb** [comment] 2020-04-14 05:54
Also, i'm hearing good things about 2019.3.9 and metal. Would be curious to know if that version improves this situation..

**Comment by daleeidd** [comment] 2020-07-07 09:42
I quickly tested this and couldn't reproduce on my 2014 MacBook Pro. Shadows didn't appear to have noticeable performance cost. Adding Flow and Dynamic Waves did, but nowhere near as described here. Please reopen if you continue to experience this issue on latest Crest URP.

**Closed by daleeidd** 2020-07-07 09:42 UTC
Labels: LWRP, bug, metal
