### ISSUE TITLE
Wandering shadows in the farout

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#612] opened 2020-08-10 20:27 UTC
**Describe the bug**
The further the camera is away from x/z = 0 about 500 - 1000 units the stronger this effect is.
As the camera is moving the shadows on the water begin to float away from the object every 2 seconds or so.

**Screenshots / video**
http://clients.kobald.com/dyb/show/crest-wandering-shadows.mov

**Versions**
URP, Unity 2019.4

**To Reproduce**
don´t know, if this happens in the test scenes. 
Set the camera way 2000 units from center and compile for iOS.

**Platform**
 not happening in editor
happening on iOS (android not tested)

**Hardware**
iPad

**Comment by daleeidd** [comment] 2020-08-10 21:38
Does it happen on a PC or Mac build?
Have you viewed the LOD data in the debug GUI?

**Comment by klauskobald** [comment] 2020-08-10 22:41
I am building for iOS on Mac. 
In fact the shadowmaps look kind of broken on ios:
http://clients.kobald.com/dyb/show/crest-shadow-debug-ipad.mov

same area on mac editor:
http://clients.kobald.com/dyb/show/crest-shadow-debug-editor.mov

**Comment by klauskobald** [comment] 2020-08-10 22:43
I am building for iOS on Mac. 
In fact the shadowmaps look kind of broken on ios:
http://clients.kobald.com/dyb/show/crest-shadow-debug-ipad.mov

same area on mac editor:
http://clients.kobald.com/dyb/show/crest-shadow-debug-editor.mov

**Comment by klauskobald** [comment] 2020-08-10 22:43
I am building for iOS on Mac. 
In fact the shadowmaps look kind of broken on ios:
http://clients.kobald.com/dyb/show/crest-shadow-debug-ipad.mov

same area on mac editor:
http://clients.kobald.com/dyb/show/crest-shadow-debug-editor.mov

**Comment by klauskobald** [comment] 2020-08-10 22:43
I am building for iOS on Mac. 
In fact the shadowmaps look kind of broken on ios:
http://clients.kobald.com/dyb/show/crest-shadow-debug-ipad.mov

same area on mac editor:
http://clients.kobald.com/dyb/show/crest-shadow-debug-editor.mov

**Comment by klauskobald** [comment] 2020-08-10 22:43
I am building for iOS on Mac. 
In fact the shadowmaps look kind of broken on ios:
http://clients.kobald.com/dyb/show/crest-shadow-debug-ipad.mov

same area on mac editor:
http://clients.kobald.com/dyb/show/crest-shadow-debug-editor.mov

**Comment by klauskobald** [comment] 2020-08-10 22:43
I am building for iOS on Mac. 
In fact the shadowmaps look kind of broken on ios:
http://clients.kobald.com/dyb/show/crest-shadow-debug-ipad.mov

same area on mac editor:
http://clients.kobald.com/dyb/show/crest-shadow-debug-editor.mov

**Comment by klauskobald** [comment] 2020-08-10 22:43
I am building for iOS on Mac. 
In fact the shadowmaps look kind of broken on ios:
http://clients.kobald.com/dyb/show/crest-shadow-debug-ipad.mov

same area on mac editor:
http://clients.kobald.com/dyb/show/crest-shadow-debug-editor.mov

**Comment by klauskobald** [comment] 2020-08-10 22:43
I am building for iOS on Mac. 
In fact the shadowmaps look kind of broken on ios:
http://clients.kobald.com/dyb/show/crest-shadow-debug-ipad.mov

same area on mac editor:
http://clients.kobald.com/dyb/show/crest-shadow-debug-editor.mov

**Comment by klauskobald** [comment] 2020-08-10 22:43
I am building for iOS on Mac. 
In fact the shadowmaps look kind of broken on ios:
http://clients.kobald.com/dyb/show/crest-shadow-debug-ipad.mov

same area on mac editor:
http://clients.kobald.com/dyb/show/crest-shadow-debug-editor.mov

**Comment by klauskobald** [comment] 2020-08-10 22:43
I am building for iOS on Mac. 
In fact the shadowmaps look kind of broken on ios:
http://clients.kobald.com/dyb/show/crest-shadow-debug-ipad.mov

same area on mac editor:
http://clients.kobald.com/dyb/show/crest-shadow-debug-editor.mov

**Comment by klauskobald** [comment] 2020-08-10 23:08
I want to emphasize: the effect increases with distance from world center 0,0,0. So there must be a kind of math flaw somewhere.

**Comment by klauskobald** [comment] 2020-08-10 23:08
I want to emphasize: the effect increases with distance from world center 0,0,0. So there must be a kind of math flaw somewhere.

**Comment by daleeidd** [comment] 2020-08-10 23:41
Sorry. I meant have you also experienced this on a mac or pc build? Just so we can have something to work with. It is possible that mac standalone might also have this issue.

> the effect increases with distance from world center 0,0,0

Are you using the floating origin script? Do any of the other shadows or lights flicker or behave strangely at this distance?

**Comment by klauskobald** [comment] 2020-08-11 00:38
I will have to build for mac. that takes 1 hour!

I did not know about the floatingOrigin script. I tried it out now on the main camera but it screws up everything. I have additive scenes which contain the terrain which is loaded via addressables, I have 2 oceansystem where the selected one gets instanciated somewhen, I have scenes created from prefabs from json data when user loads a scene. 

So, I actually thought about doing the same thing, but I thought I could simply move the crest center?

**Comment by klauskobald** [comment] 2020-08-11 00:38
I will have to build for mac. that takes 1 hour!

I did not know about the floatingOrigin script. I tried it out now on the main camera but it screws up everything. I have additive scenes which contain the terrain which is loaded via addressables, I have 2 oceansystem where the selected one gets instanciated somewhen, I have scenes created from prefabs from json data when user loads a scene. 

So, I actually thought about doing the same thing, but I thought I could simply move the crest center?

**Comment by klauskobald** [comment] 2020-08-11 02:25
it´s not happening in a mac os player.

**Comment by klauskobald** [comment] 2020-08-11 17:18
Moving crest center does not help. That´s why you have this floatOrigin in place, right? The default distance threshold there is 16384 ! So, did you assume, that this would be the distance, where floatingpoint issues would start? It´s happening with distances around 500 actually. Anyway, I do not know how I would get this to work. I tried to activate it, when my scene-loaded event is triggered and deactivate it before scene is loaded. But it screws up everything.
Why is this all necessary in the first place? Can we fix the math somehow and where?

**Comment by klauskobald** [comment] 2020-08-11 17:27
sidenote: 
` 
// Gerstner components
                var gerstners = _overrideGerstnerList != null && _overrideGerstnerList.Length > 0 ? _overrideGerstnerList : FindObjectsOfType<ShapeGerstnerBatched>();
                foreach (var gerstner in _overrideGerstnerList)
                {
                    gerstner.SetOrigin(newOrigin);
                }
`

gerstners is never used!

**Comment by daleeidd** [comment] 2020-08-11 18:17
> That´s why you have this floatOrigin in place, right?

The floating origin script is based on a community script that many use to solve floating point precision problems. We integrated Crest with it so they can be used together. If you do use it, there may some new problems to solve so you project integrated with it correctly. But it doesn't sound like this issue is related. Just trying to rule things out.

> The default distance threshold there is 16384 ! So, did you assume, that this would be the distance, where floatingpoint issues would start?

Generally, Unity floating point precision issues (lights and shadows will flicker etc) start around then.

> Can we fix the math somehow and where?

Possibly. It could be a Unity bug on specific hardware which would be difficult to fix from our end. With URP we aren't doing anything special.

Could you try adding a shadow sim settings and setting the jitter to zero (or greater than zero if it is already zero) and see if it makes a difference? I don't think this will make a difference but I have experienced some oddities with this.

Have you been able to reproduce this with the main scene? You can try moving the main scene objects as far out as you need to reproduce.

**Comment by klauskobald** [comment] 2020-08-11 18:29
well, it´s strange: there is a "landscape" gameobject in the additive scene, that gets moved arround correctly, but some of it´s children do not get translated where the terrain, which is also a child, does get translated. I will have to look into that.

I can control the shadow sim via remote config and tried all kind of values. It does not change that floating away shadows. As wrote above: the debug shows complete "broken" textures.

So, if this is a unity bug which would not make me wonder, maybe to go with that workarround is the way to go. It´s only: I thought, I am finished :-)  . If I knew that before, I would have designed things differently.

**Comment by klauskobald** [comment] 2020-08-11 19:05
I wonder what happens to all the lightmaps and occlusionmaps, when terrain gets moved around. Did anybody think of that?

**Comment by klauskobald** [comment] 2020-08-11 19:23
static objects do not get translated except for terrain. so I wonder what implication that will have if I change everything to non static.

**Comment by klauskobald** [comment] 2020-08-11 20:27
I made more tests: static batching prevents the objects from being moved. So that is solved, but the whole concept does not work, which was obvious to me: all occlusion and lightmap data gets out of place. So we have to come up with a real fix. 
I will turn off shadows which is a big bummer but I can´t stand it any more - I have to make a release.

**Comment by klauskobald** [comment] 2020-08-11 20:30
if this really a Unity bug, can you please open an issue? I do not even know where I would point them to!

**Comment by daleeidd** [comment] 2020-08-11 22:06
The difficulty is that I don't have a device for reproducing this issue. Unity will want a minimal, reproducible case. Sometimes there will be back and forth too as you have experienced.

If you have access to some sort of frame debugger for iOS, that would be the ideal. Then you could inspect the shadow map texture.

I am guessing that producing iOS builds is time consuming? Otherwise, I would suggest to use the problem scene to try and narrow it down further. Making the ocean transparent so you can see shadows on the terrain might be revealing. It could either be the shadow maps are wrong or one of the matrices we use to transform coordinates.

**Comment by klauskobald** [comment] 2020-08-11 23:23
I think, the shadow map is fine. You can see the correct shadow at the ocean ground.
http://clients.kobald.com/dyb/show/crest-shadow-check.mov
This is highest quality with 4 cascades. But it´s the same for 2 cascades.
I added 2 images, that show that your shadowmaps (are they from crest?) look kind of broken when far away (>500m) from the center.

Build for iOS is not so time consuming once all the assets are converted. A few minutes sometimes faster. But do you think I need to frame debug? For me it seems, as if there is a mistake by copying the textures. Please tell me: what code parts are involved?

**Comment by daleeidd** [comment] 2020-08-12 16:28
The following files will be of interest for shadows:
/Assets/Crest/Crest/Shaders/Resources/UpdateShadow.shader
/Assets/Crest/Crest/Scripts/LodData/Shadows/SampleShadows.cs
/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs

It is most likely a problem with the first file which is the shader which samples the shadow maps and populates those render textures. The second won't be of much interest.

An example of sampling shadows for URP can be found in the screen space shadows file:
/Library/PackageCache/com.unity.render-pipelines.universal@7.3.1/Shaders/Utils/ScreenSpaceShadows.shader

For testing purposes, you could replace most of the contents in UpdateShadow with ScreenSpaceShadows and screen space shadows will render into the render texture. It could provide some insights.

**Comment by daleeidd** [comment] 2020-08-12 16:40
> I added 2 images, that show that your shadowmaps (are they from crest?) look kind of broken when far away (>500m) from the center.

They are our shadow data. We just sample Unity's shadow maps (and apply some jitter etc).

> But do you think I need to frame debug?

It could help if you have access to one just in case there is something wrong with Unity's data.

**Comment by klauskobald** [comment] 2020-08-12 17:07
but why, are the "normal" shadows correct, if the unity shadowmaps are wrong.

**Comment by daleeidd** [comment] 2020-08-12 19:03
Unity data can also mean one of their matrices. UpdateShadow executes at a different point in the pipeline than opaque objects so it is not impossible that something could be wrong.

**Comment by klauskobald** [comment] 2020-08-12 19:40
Is there a way we could do a hackathon for 1 or 2 hours with zoom or jitsi or something? I would need a guided tour on how that shader works. Every little change I try means compile the whole thing and wait. That would take me forever. Together we could change the right lines and see what impact it has.

**Comment by huwb** [comment] 2020-08-13 06:29
Could you please apply these settings (create a shadow settings object, apply to shadow settings field on ocean object) and capture a video like the first video you captured in the original post?

![image](https://user-images.githubusercontent.com/939901/90101235-3e373780-dd36-11ea-836a-1afda1ff736c.png)

Does anyone know a way to visualise the unity shadow maps in build? If needed we could probably write one, but it would be nice if someone else did this already..

**Comment by huwb** [comment] 2020-08-13 07:29
Also it could be a precision issue and theres quite a few half/half2/half3's in the UpdateShadow.compute shader.

The ones that look most suspicious to me are these (although i'm fairly sure this is derived from unity code):

`
	half4 ShadowCoord0_dxdz;
	half4 ShadowCoord1_dxdz;
	half4 ShadowCoord2_dxdz;
	half4 ShadowCoord3_dxdz;
`

In addition to the video requested above, could you try setting these to floats? If that doesnt help could you search replace any other half's in the shader to float?

**Comment by daleeidd** [comment] 2020-08-13 14:59
@klauskobald I won't be able to. We should be able to grasp the issue without it though

**Comment by klauskobald** [comment] 2020-08-13 17:01
This video shows editor (left) and iPad(right) with the same shadow-settings:
http://clients.kobald.com/dyb/show/crest-2020-08-13_12-39-04.mp4
You will also see a flickering in the editor which is caused by a  low frame rate, which is caused by the bad programmed remote config interface from Unity. Even with a high framerate, it seems, that shadows are only drawn every other frame.

A currentFrameWeightHard=1 in fact eliminates the wandering away shadow at the cost of flickering and not very smooth shadows. That was the reason I used a very small number 0.1 for this.
You can see this in the video at 0:33 - flickering stops: but iPad produces wandering shadow 0:49.

I also tried to change all halfs to floats in the shader, but that did not change anything.

**Comment by huwb** [comment] 2020-08-13 20:05
I think flicker might be a separate issue, that may be editor only. Dale does this sound right?

Klaus could you please apply all the settings from my screenshot, make the shadow data visible in the debug gui, and move the camera around a bunch (quickly and slowly), in the build (not editor). Need to be able to clearly see the "wandering" effect with those settings and shadow data visible.

**Comment by daleeidd** [comment] 2020-08-13 22:35
> I think flicker might be a separate issue, that may be editor only. Dale does this sound right?

It does. I don't think I have seen it before though.

**Comment by klauskobald** [comment] 2020-08-14 01:12
![shadowsettings](https://user-images.githubusercontent.com/278428/90200992-85a9dc00-dda7-11ea-862f-d875b40ea5de.jpg)
But with these settings there is no wandering effect but flickering! So I included variants for the videos.

http://clients.kobald.com/dyb/show/shadowmaps/

I made variations: jitter diameter is always 0.
the first number in the filename is currentFrameWeightSoft the second is currentFrameWeightHard
farout : x/z=400/1900 -> wandering shadows when currentFrameWeight = 0.1
center: x/z=625/-380 (well not really center - but I found closer) -> no wandering shadows

**Comment by huwb** [comment] 2020-08-14 06:22
@daleeidd in case your brain is as tired as mine - the "1-1" videos are the ones that correspond with the requested settings

That's quite a result. Very colourful!

I need to think about whats happening there. Looks like unbound texture/graphical corruption type stuff. On the other hand, it "sort of" matches the right shadow shape. So i'm pretty confused. Maybe visualising the shadowmaps somehow is a good next step.

Just to check, is your boat set to shadow caster? I think it is but just checking.. we have an issue where if theres no shadow caster on screen the shadows may stop updating. that doesnt really explain the videos though!

Could you post the same thing running from mac editor. Only game view visible (not scene view). Only the requested settings (above) please. With shadow data visible again.

**Comment by huwb** [comment] 2020-08-14 06:23
Oh and could you be sure to move the camera around a bit more such as orbiting. Mix of slow and fast would be ideal. Thanks!

**Comment by huwb** [comment] 2020-08-14 08:13
Oh and in addition to setting the halfs to floats in updateshadows.shader , could you also replace 'real' with float. Real is half on mobile.

I'm not confident this will fix it but I think it's safest to use full precision for now.

As an additional test, could you remove the shadowStrength variable and everything below it, and just add a

return shadowThisFrame;

Basically knock out a chunk of the shader to see if the crazy patterns go away.

Requests, could we use this numbering for videos:

1 video from editor, details described above in my last post
2 video from build, far from origin, settings described above, shadow data visible, with the second half of the shader removed (return shadowThisFrame)

**Comment by klauskobald** [comment] 2020-08-14 15:11
ok. so, I think we are DONE !!!!!!!!!
replacing real with float fixed it. the halfs seem to be ok to use. 
all textures look clean now. the flickering can be smoothed by reducing the frameWeight number to 0.5.
question is, how much memory impact that has on GPU and if we should search for the bad guy.

so, if you still want to look into the flickering I think that´s another story which should also be visible in your editor. i will open a ticket for that.

for me this issue is closed!
(If I only knew before that real is half!)

**Comment by klauskobald** [comment] 2020-08-14 15:42
.... interesting: changing all floats to halfs does not produce the effect in the editor. (Mac)

**Comment by huwb** [comment] 2020-08-15 14:56
Mac will ignore the 'half' directive and always use floats.

I'm not sure how much you want to poke around with this, but floats are more expensive than half's, so ideally we only use floats where they are absolutely needed. It would be good to know if there are particular variables that need to be floats, and leave the rest as halfs. I'd guess its one or multiple of these:

```
				real4 positionCS : SV_POSITION;
				real4 _MainCameraCoords : TEXCOORD0;
				real3 _WorldPos : TEXCOORD1;
```

Anyway just mentioning in case you want to narrow it down. If not @daleeidd we should probably decide what we want to do. i guess just making everything float is the easy option, and should not affect our normal supported platforms.

In any case glad to hear this resolved it!

**Comment by huwb** [comment] 2020-08-15 15:08
(actually _WorldPos should always be float not half so i'll make that change)

**Comment by klauskobald** [comment] 2020-08-15 16:53
I will make more tests maybe next week.

**Comment by daleeidd** [comment] 2020-08-16 19:51
> It would be good to know if there are particular variables that need to be floats, and leave the rest as halfs.

https://docs.unity3d.com/Manual/SL-DataTypesAndPrecision.html

I also had a look through the Universal pipeline package to see what Unity does and they would make these three floats too. And they have been making positionOS float too.

**Comment by huwb** [comment] 2020-08-16 20:21
Ah good shout. I replaced them with floats and pushed that now.

I also searched all files for "real3 positionOS" and fixed them up.

Lets close this when 4.5 goes live (submitted now)

**Comment by daleeidd** [comment] 2020-08-17 15:33
URP 4.5 is out with these fixes

**Closed by daleeidd** 2020-08-17 15:33 UTC
Labels: URP, bug, metal

**Comment by klauskobald** [comment] 2020-08-18 01:53
4.5 works!
