### ISSUE TITLE
[HDRP] Underwater draws through buildings

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#479] opened 2020-04-22 07:06 UTC
**Describe the bug**

Discord user Puppetmaster reported an issue where the underwater effect appears through a building:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/939901/79950328-d13e2000-846e-11ea-8982-6c8d6b73098f.gif)

He suggests it may have been introduced in Crest HDRP 4.1.

It might be that the surface is being culled by unity using dynamic occlusion culling. These tiles wont be added to the visible list, and therefore won't be registered to draw into the ocean mask. However I could not reproduce this effect locally.

Actually, maybe this is due to multiple water levels. I've enquired.

**Versions**
Unity 2019.3.9
Crest HDRP 4.1

**To Reproduce**
How can the developers reproduce this bug? Are you able to reproduce the issue in the example content/scenes?
Please include steps to reproduce the behaviour, with the example content ideally so we can follow the steps on our side.

**Platform**
 - Editor or standalone?
 - Platform (win/mac/...)

**Hardware**
What hardware are you seeing the issue on? GPU model is particularly useful.

**Additional context**

**Comment by Puppetmaster3Dxxx** [comment] 2020-04-22 10:19
My specs:
- Win 10 pro
- 2x Nvidia GTX 2080ti
- Unity 2019.3.9f, HDRP 7.3.1
- Crest 4.1 (from the Package Manager in Unity)

The Problem does only occur when I use Occlusion baking in Unity with those settings:
Smallest Occluder: 1
Smallest Hole: 0.1
Backface Threshold: 75

As soon as I clear the baked occlusion, the problem is also gone.  I made video for you.

[2020-04-22_12-14-07.zip](https://github.com/crest-ocean/crest/files/4515450/2020-04-22_12-14-07.zip)

**Comment by banan5555** [comment] 2020-04-22 12:05
This is same case like ours:
https://github.com/crest-ocean/crest/issues/456

And problem is not only with occlusion culling.
Small line without occlusion culling:
![crest-horizonline-issue1](https://user-images.githubusercontent.com/63231118/79979659-234c6900-84a2-11ea-91ef-ffebdb0e25a6.png)

Big line with occlusion culling:
![crest-horizonline-issue2](https://user-images.githubusercontent.com/63231118/79979713-3c551a00-84a2-11ea-8582-d109eda709a4.png)

**Comment by moosichu** [comment] 2020-04-22 16:48
The underwater mask depends on a contiguous ocean surface being rendered. We've been unable to reproduce these issues ourselves. If anyone is up for it, a RenderDoc capture could be really helfpul here. If you don't know what that is I'm more than happy to explain and walk people through the steps.

**Comment by huwb** [comment] 2020-04-22 17:30
After messing around i found a repro here - at runtime disable one of ocean tiles in the mid or background by setting the gameobject inactive, then put the camera looking through the island in main.unity (close-ish to the water so underwater is active):

![image](https://user-images.githubusercontent.com/939901/80013820-61a84f00-84c7-11ea-974a-96172705ac57.png)

**Comment by banan5555** [comment] 2020-04-22 19:15
@moosichu here is my RenderDoc capture with simplest case - cube and crest:
https://drive.google.com/open?id=1pVeoXQmxYFJBasGQ5qyrm2nKmM3-SThM

screen:
![image](https://user-images.githubusercontent.com/63231118/80023822-69bfb900-84de-11ea-9d47-549e851872cc.png)

**Comment by moosichu** [comment] 2020-04-22 21:24
We are working on a solution to both problems. This is seprate from the horizon line issue, but both are being worked on :)

**Comment by moosichu** [comment] 2020-05-23 17:45
I thought this was fixed but managed to repro it, have a fix incoming.

**Comment by daleeidd** [comment] 2020-06-17 09:34
4.3 is out with a fix for this. Please reopen if you still experience this issue

**Closed by daleeidd** 2020-06-17 09:34 UTC
Labels: HDRP, bug

**Comment by originalemanuel** [comment] 2020-06-17 11:09
> 
> 
> 4.3 is out with a fix for this. Please reopen if you still experience this issue

is it available in the asset store?

**Comment by daleeidd** [comment] 2020-06-17 11:21
@originalemanuel Yes
