### ISSUE TITLE
GPU error (ComputeShaderQueries) with more than 16 floating objects

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#491] opened 2020-04-28 23:20 UTC
**Describe the bug**

I get this error on iPad and the app freezes:
2020-04-28 19:10:50.223337-0400 crest-test[37911:10569854] Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (IOAF code 5)

I found out that it happens when adding more than 16 gameobjects with the SimpleFloatingObject script attached. 

**Log**
It´s not happening in editor

**Versions**

Unity 2019.3.10, URP 7.3.1

**To Reproduce**

add 17 floating objects

**Platform**
iOS 

**Hardware**
 iPad Pro, iPad Air 2

**Comment by klauskobald** [comment] 2020-04-29 00:15
UPDATE:
The number of floating objects is only triggering the problem. it seems to have something to do with SimSettingsAnimatedWaves.
When I select "Gerstner Wave" instead of "Shader ..." it seems to work. So what is the difference? And how will this affect mobile devices with less CPU power?

**Comment by klauskobald** [comment] 2020-04-29 00:36
UPDATE:
It also works when SimSettingsAnimatedWaves is set to "None". What for is that thingy?

**Comment by klauskobald** [comment] 2020-04-29 01:41
I have limited the fixedupdate to 3 times per second, but that did not solve the problem. App hangs after a second. So I give up for now.

**Comment by daleeidd** [comment] 2020-04-30 02:01
Thank you for reporting. Can you please provide the iOS version? I have seen similar reports of this issue for the Post-Processing Stack.

> When I select "Gerstner Wave" instead of "Shader ..." it seems to work. So what is the difference?

I believe that wave attenuation only works with compute shader queries. You could try reducing the max query count, but I think that will only post pone the issue.

This might be a bug in Unity and Metal
https://github.com/Unity-Technologies/PostProcessing/issues/727

It might be possible that Unity isn't managing this correctly. I am not sure if this is something we can solve.
[Metal Best Practices Guide: Command Buffers](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/CommandBuffers.html#//apple_ref/doc/uid/TP40016642-CH29-SW1)

**Comment by daleeidd** [comment] 2020-04-30 02:29
Also, for obtaining logs, either of these might help:
https://docs.unity3d.com/Manual/LogFiles.html
https://forum.unity.com/threads/how-to-capturing-device-logs-on-ios.529920/

**Comment by daleeidd** [comment] 2020-04-30 02:34
And are you creating these floating objects at runtime (one at a time or in a bunch)?

**Comment by klauskobald** [comment] 2020-04-30 04:30
iOS: 13.3.1 on all devices. 
For test reasons I create one object per second and after the 16th system stalls - mostly - sometimes sooner than that. I also have 9 flow regions with 9 different flow shaders + waves and a complex terrain. Honestly, I was hoping that buying the asset would keep problems away from me. But anyhow, your project is worth it and I understand that things are very complex. 
I will dig into it tomorrow again (I am in Sint Maarten - 5hrs behind UK) and will try to gain more understanding on how that all works.  As a last resort I can optionally live with the CPU based height sampling and interpolate over time as I did with the comunity ocean shader. I am modeling slow sailboats, so sampling the height and flow 4 times per second is enough.
I will also try Unity 2020.1 - maybe that helps.

**Comment by klauskobald** [comment] 2020-04-30 16:07
So far no luck. Similar error on Unity 2020.1. 
By the way the first GPU errors are these:
Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)

**Comment by klauskobald** [comment] 2020-04-30 20:36
I started from scratch and took your threeboats scene. There I duplicated the BoatAlignNormal Boats to get about 30. Same thing: GPU hangs after first frame.
So I will end investigation now and will use the CPU version for ocean queries. I hope anybody can fix this in the next months.

**Comment by daleeidd** [comment] 2020-05-01 05:09
Thanks.

> I started from scratch and took your threeboats scene. There I duplicated the BoatAlignNormal Boats to get about 30

I tried this scenario and I wasn't able to reproduce hitching on Mac. I believe it must be a Unity bug.

I have had an ongoing issue with hitching on this Mac Mini with Crest, but it was concluded that it is most likely a Unity bug with Metal rather than something with Crest as I have experienced it without Crest too. Unfortunately, I don't have an iOS test device.

If you have a solid reproducible case, could you please submit a Unity bug? I believe this is our best approach to having this progress further for the time being.

**Comment by daleeidd** [comment] 2020-05-01 05:11
Also, I forgot to ask what version of Crest are you using?

**Comment by klauskobald** [comment] 2020-05-01 12:08
crest V 4.1
Yes, it is an iOS problem only! Am I the only one running into that error?
Are there any parameters I could tweak? Like buffersizes or whatever?
I can try submit, but that would mean, that I will have to expose the code as I will have to submit the project.

**Comment by daleeidd** [comment] 2020-05-01 15:21
Thanks for that.

> Yes, it is an iOS problem only! Am I the only one running into that error?

This is the first I have heard of this specific case. There are others successfully using Crest on iOS. Unity has a lot of issues on Metal from my own experience.

> I can try submit, but that would mean, that I will have to expose the code as I will have to submit the project.

You could export the scene with the reproducible case (the three boats scene you created) and Crest into a new project and submit that using _Help > Report a Bug..._? If you do, make sure it to do it through the latest stable Unity version as they prioritise bugs on latest versions.

**Comment by klauskobald** [comment] 2020-05-01 17:45
I filed a bugreport now.

**Comment by moosichu** [comment] 2020-05-02 08:09
Please let us know how you get on!

**Comment by daleeidd** [comment] 2020-05-22 19:49
@klauskobald Thanks! Saw that this was posted on discord

https://issuetracker.unity3d.com/issues/ios-metal-gpu-hangs-on-queries-made-to-metal-api-throwing-errors-every-frame-when-a-certain-amount-objects-is-being-rendered

**Comment by akeidonas** [comment] 2020-06-16 12:50
Howdy,

The cause of the problem is in QueryBase.cs:
>var numGroups = (int)Mathf.Ceil((float)_segmentRegistrarRingBuffer.Current._numQueries / (float)s_computeGroupSize) * s_computeGroupSize;

What happens when numQueries gets to 65 - you get numGroups 128, and then dispatched CS tries to write 128*64 float3s to the output buffer (buffer size is 4096 float3s) - out of bounds writes.
Currently you're always running at least 64 threadGroups (which is also the maximum of groups >> 4096/64)

numGroups should just be (_segmentRegistrarRingBuffer.Current._numQueries + s_computeGroupSize - 1) / s_computeGroupSize

Cheers

**Comment by huwb** [comment] 2020-06-16 12:58
Yeah that looks correct! Well spotted!

@daleeidd could you please test with that change and see if it fixes the issue for you, and if so create a PR? Thanks!

**Comment by daleeidd** [comment] 2020-06-17 02:47
@huwb done. I could never reproduce the exact issue. And the issue (crazy boats) I reported hasn't been solved by this.

I noticed something odd to me when testing: it throws an exception when _\_segmentRegistrarRingBuffer.Current.\_numQueries_ exceeds the __maxQueryCount_. We have a check against __maxQueryCount_ by `_requests.Count >= _maxQueryCount` (line 439), but __requests.Count_ doesn't match __segmentRegistrarRingBuffer.Current.\_numQueries_.

**Comment by huwb** [comment] 2020-06-17 06:48
Hmm ok could you please create a new pr for that with the exception and call stack pasted in? I haven't completely understood yet

**Comment by daleeidd** [comment] 2020-07-07 09:55
This should be fixed in 4.4. Please reopen if you are still experiencing this issue. Thanks!

**Closed by daleeidd** 2020-07-07 09:55 UTC
Labels: bug, metal
