### ISSUE TITLE
Enable Screen Space Reflections (HDRP)

### ISSUE THREAD

**Issue by dampete** [crest-ocean/crest#689] opened 2020-11-16 15:35 UTC
Ocean currently does not work with SSR in HD render pipeline.

Here's a screenshot with a ship and Crest, SSR enabled and no reflections.
![image](https://user-images.githubusercontent.com/4088359/99273538-ef52df80-2807-11eb-9a9d-a5a545f13b7b.png)

Here's the same setup, just added a reflective quad underneath the ocean surface to capture the reflection.
![image](https://user-images.githubusercontent.com/4088359/99273678-1c9f8d80-2808-11eb-8bad-f5531ab854c7.png)

**Comment by huwb** [comment] 2020-11-18 13:43
Unfortunately I believe it is a hdrp limitation - no SSR on transparent materials. 

https://forum.unity.com/threads/ssrr-on-a-transparent-or-translucent-object.408206/

**Comment by daleeidd** [comment] 2020-11-18 16:07
@huwb It looks like they added it in HDRP 10. According to the [changelog](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.0/changelog/CHANGELOG.html):

> Added of Screen Space Reflections for Transparent materials

**Comment by huwb** [comment] 2020-11-22 10:59
Ha thanks. Hopefull it will work then (when testing, definitely worth trying flat/calm water first). Can reopen this until one of us gets the chance to try it out.

**Comment by galfaroth** [comment] 2020-11-22 21:18
I up this one, a tutorial/vid on SSR and Crest for HDRP would be a good start.

**Comment by daleeidd** [comment] 2021-01-06 18:12
Closing this one as it is a duplicate of issue #613. Oops

**Closed by daleeidd** 2021-01-06 18:12 UTC
Labels: HDRP
