### ISSUE TITLE
[HDRP] 256 shader keyword limit exceeded

### ISSUE THREAD

**Issue by fikoljuky** [crest-ocean/crest#547] opened 2020-06-16 06:38 UTC
Hey. I was advised by Dale on the discord to open up a issue. It's happenig to me in the unity version in the titel on the latest version of chrest. 

Unity 2019.4.0f1 HDRP ver 7.3.1.

> Maximum number (256) of shader global keywords exceeded, keyword CREST_CAUSTICS_ON will be ignored.
> Maximum number (256) of shader global keywords exceeded, keyword CREST_FLOW_ON will be ignored.
> Maximum number (256) of shader global keywords exceeded, keyword CREST_FOAM_ON will be ignored.
> You will have to delete some shaders or make them use less keywords.
Keywords used in project now: _SHADOWS_SOFT _DETAIL_MAP1 _MIXED_LIGHTING_SUBTRACTIVE _SMOOTHROUGH_ON VARIANT8 FOG_OFF VARIANT14 SPOT VARIANT4 VERTEXLIGHT_ON VARIANT3 _LIGHTMAPPING_STATIC_LIGHTMAPS LIGHTPROBE_SH DECALS_4RT _HEIGHTMAP0 _NORMALMAP2 _TERRAIN_INSTANCED_PERPIXEL_NORMAL _SURFACE_TYPE_TRANSPARENT LIGHT_LAYERS _MASKMAP0 UNITY_COLORSPACE_GAMMA TONEMAPPING_NEUTRAL FXAA_LOW AUTO_KEY_VALUE GLOW_ON CREST_DIRECT_TOWARDS_POINT_INTERNAL _EMISSION SHADOW_HIGH _THICKNESSMAP2 _THICKNESSMAP1 _MASKMAP3 BILLBOARD_FACE_CAMERA_POS VARIANT16 CHROMATIC_ABERRATION _USEDYNAMICSNOWTSTATICMASKF_ON _ENABLEROTATION_ON _USE_GRADIENT_ON _IGNOREGRASSFADE _SUBSURFACE_MASK_MAP0 _SSSFROMALPHA_ON APPLY_FORWARD_FOG UNITY_UI_CLIP_RECT _HASNOISEEMISSIVE_ON DEBUG_DISPLAY LOD_FADE_PERCENTAGE _INTERPOLATE_LAYERS_ON COLOR_GRADING_HDR USER_LUT DIRECTIONAL_COOKIE SOURCE_GBUFFER SHADOWS_SHADOWMASK HEIGHT_FOG GRAIN MATERIAL_QUALITY_MEDIUM FXAA VARIANT28 _USENORMALMAP_ON USE_MIS SHADOW_LOW _ENABLESPECULAROCCLUSION LIGHTMAP_ON _NORMAL _ALPHATEST_ON INSTANCING_ON COLOR_GRADING_LDR_2D WRITE_NORMAL_BUFFER _SUBSURFACE_MASK_MAP2 TOUCH_BEND_ON _SHADOWS_ON EFFECT_HUE_VARIATION BLOOM _HEIGHTMAP1 DIRLIGHTMAP_COMBINED VARIANT7 _WINDQUALITY_BEST _CAUSTICS_ON SAMPLES_HIGH UNITY_SINGLE_PASS_STEREO SAMPLES_ULTRA STEREO_INSTANCING_ON WRITE_MSAA_DEPTH _NORMALMAP0 _CAMERADISTANCEFADE_ON SHADOWS_SOFT OUTPUT_SPLIT_LIGHTING _FEATHERATUVEXTENTS_ON VARIANT5 _MASKMAP _RECEIVE_SHADOWS_OFF VARIANT18 TONEMAPPING_ACES ENVIRO_SIMPLE_FOG SHADOWS_SINGLE_CASCADE _MIXMODE_SOFTMERGE _COVERAGEFADE_ON CHROMATIC_ABERRATION_LOW TONEMAPPING_FILMIC VARIANT23 _SMOOTHFROMMAPSWITCH_ON FXAA_KEEP_ALPHA VIGNETTE AUTO_EXPOSURE GPU_FRUSTUM_ON VARIANT20 _OCCLUSIONMAP WATER_REFRACTIVE _BENTNORMALMAP3 _COMPILESHADERWITHDEBUGINFO_ON _HEMI_ON UNDERLAY_ON _BENTNORMALMAP0 SHADOWS_CUBE FOG_EXP _DEBUG_MASK_ON _FULL_SCREEN_EFFECT _NORMALMAP3 TRANSPARENT_COLOR_SHADOW _MIXMODE_RANDOM VIGNETTE_MASKED SAMPLES_MEDIUM _ENABLEFOG_ON _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A USE_CLUSTERED_LIGHTLIST FOG_LINEAR SHADOWS_SCREEN _SPECULAR_OCCLUSION_FROM_BENT_NORMAL_MAP PROCEDURAL_INSTANCING_ON _PARALLAXMAP _DETAIL_MAP3 _HEIGHTMAP3 LIGHTMAP_SHADOW_MIXING _USESNOW_ON FAR_CULL_ON ETC1_EXTERNAL_ALPHA _NORMALMAP UNITY2017_2_SP SHADOWS_SPLIT_SPHERES _STATICHIGHLIGHTS_ON _SPECULARHIGHLIGHTS_OFF _SUBSURFACE_MASK_MAP3 _HEIGHTSONLY_ON UNITY_UI_ALPHACLIP DEPTH_OF_FIELD _MASKMAP2 VARIANT10 OUTLINE_ON CREST_DYNAMIC_WAVE_SIM_ON_INTERNAL STEREO_MULTIVIEW_ON UNITY_HDR_ON _SPECGLOSSMAP _BENTNORMALMAP2 CREST_FLOW_ON_INTERNAL _SUBSURFACESCATTERING_ON FINALPASS _MIXMODE_BYSIZE _MAIN_LIGHT_SHADOWS_CASCADE _METALLICGLOSSMAP DIRECTIONAL SAMPLES_LOW DECALS_OFF POINT DECALS_3RT DEPTH_OF_FIELD_COC_VIEW VARIANT2 _THICKNESSMAP3 _COLORADDSUBDIFF_ON _EMISSIONSWITCH_ON ENVIROVOLUMELIGHT _ALPHABLEND_ON BLOOM_LENS_DIRT VARIANT6 ANTI_FLICKER COLOR_GRADING_HDR_3D _GLOSSYREFLECTIONS_OFF _SPECULAR_OCCLUSION_NONE STEREO_CUBEMAP_RENDER_ON _SUBSURFACESHALLOWCOLOUR_ON _DEBUG_VIEW_OCEAN_MASK VARIANT11 BEVEL_ON POINT_COOKIE _UVSEC_UV1 VARIANT24 _ALPHAPREMULTIPLY_ON MATERIAL_QUALITY_HIGH DITHERING USE_FPTL_LIGHTLIST EDITOR_VISUALIZATION SHADOW_MEDIUM MULTI_BOUNCE_INDIRECT COLOR_GRADING_LOG_VIEW COLOR_GRADING WATER_REFLECTIVE _NORMALMAP1 _SUBSURFACE_MASK_MAP1 TONEMAPPING_CUSTOM SHADOWS_DEPTH VARIANT21 EFFECT_BUMP FOG_EXP2 _THICKNESSMAP0 EFFECT_EXTRA_TEX VARIANT19 _USEDETAILMAPS_ON _METALLICSPECGLOSSMAP _EMISSIVE_COLOR_MAP VARIANT25 VARIANT1 IS_DRAWPROCEDURALINDIRECT _ADDITIONAL_LIGHTS LOD_FADE_CROSSFADE _HASOPACITYNOISE_ON _BENTNORMALMAP1 _HEIGHTMAP2 DIFFUSE_LIGHTING_ONLY _MAIN_LIGHT_SHADOWS VARIANT9 MATERIAL_QUALITY_LOW _ADDITIONAL_LIGHT_SHADOWS PIXELSNAP_ON _DETAIL_MAP COLOR_GRADING_HDR_2D _DETAIL_MAP0 SOFTPARTICLES_ON BLIT_SINGLE_SLICE DISTORT VARIANT26 VARIANT27 SHOW_FEATURE_VARIANTS DISABLE_TEXTURE2D_X_ARRAY SHOW_LIGHT_CATEGORIES DIRLIGHTMAP_SEPARATE _MASKMAP1 VARIANT0 BLOOM_LOW _BENDINPUT_ATG VARIANT15 DYNAMICLIGHTMAP_ON _MENISCUS_ON _UVPRIM_UV1 _SPECULAR_SETUP WATER_SIMPLE NOISE _DETAIL_MULX2 VARIANT22 _TRANSPARENCY_ON UNITY_PASS_SHADOWCASTER VIGNETTE_CLASSIC LUXWATER_DEFERREDFOG _NORMALMAP_TANGENT_SPACE _DETAIL_MAP2 VARIANT13 UNDERLAY_INNER VARIANT12 VARIANT17 _ADDITIONAL_LIGHTS_VERTEX
UnityEngine.Material:CopyPropertiesFromMaterial(Material)
Crest.UnderwaterPostProcessUtils:UpdatePostProcessMaterial(RenderTexture, Camera, PropertyWrapperMaterial, UnderwaterSphericalHarmonicsData, Boolean, Boolean, Single) (at Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessUtils.cs:122)
Crest.UnderwaterPostProcessHDRP:Render(CommandBuffer, HDCamera, RTHandle, RTHandle) (at Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcessHDRP.cs:106)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

> TLS Allocator ALLOC_TEMP_THREAD, underlying allocator ALLOC_TEMP_THREAD has unfreed allocations, size 13156

I hope it gets fixed in a future update.

**Comment by daleeidd** [comment] 2020-06-16 08:30
@fikoljuky Thanks! If you add the following to the UnderwaterPostProcessHDRP.shader file, does it change or improve the situation for you?
```
#pragma shader_feature_local CREST_CAUSTICS_ON
#pragma shader_feature_local CREST_FLOW_ON
#pragma shader_feature_local CREST_FOAM_ON
```

It can be placed with the other `#pragma shader_feature` lines. Anywhere around there will be fine.

**Comment by daleeidd** [comment] 2020-06-16 12:20
I wasn't able to reproduce myself since this issue is generally like that unfortunately. But I have changed all these keywords to be local. This will reduce our global keyword contribution.

**Comment by fikoljuky** [comment] 2020-06-17 07:38
Hey. I will give it a go and see what happens. Thanks for the response :)

**Comment by fikoljuky** [comment] 2020-06-19 09:05
Dale I removed the keywords from some other shaders and it seamed to stop the issue, So I would say it's due to the 256 cap in general, not just Crest related.

**Comment by daleeidd** [comment] 2020-07-07 09:21
@fikoljuky Sorry. I must of missed the notification for this. Thanks for the feedback. It is good for us to reduce our global keyword usage.

4.4 is out so I will close this. Thanks! :)

**Closed by daleeidd** 2020-07-07 09:21 UTC
Labels: HDRP, bug
