### ISSUE TITLE
Mask/Cutout Ocean

### ISSUE THREAD

**Issue by holdingjason** [crest-ocean/crest#77] opened 2018-09-24 21:38 UTC
Not sure if this has come up but wondering if we had a proper way to not render/cut out an area of the ocean.  Basically we need a way to be able to go below the ocean plane around certain areas of the terrain, caves whatever.

I guess one way would be to apply something similar to how we flatten the ocean out near shores but actually push it down further on the y.

**Comment by gamemachine** [comment] 2018-09-24 23:06
While I'm assuming a depth mask would work for this, I would propose a bounds based solution that clips geometry based on worldspace bounds passed to the shader.   I have some existing code that goes this I could share, I use it for dynamic entrances into terrains.

The issue with depth masks is aligning them to geometry.  You have to do it exact or you get artifacts of various types, and it's impossible to do well really.

**Comment by gamemachine** [comment] 2018-09-24 23:14
Gist with the core functionality.  Encode bounds min/max in a float4 you pass to the shader, and call this function with that float4 and world position.  You can pass a vector array also and then loop over several.  It's not really that expensive, especially not in comparison to the overall cost of the water.

https://gist.github.com/gamemachine/d97869b20046c2f3b515679f4c7b266f

**Comment by holdingjason** [comment] 2018-09-24 23:51
That makes a lot of sense actually.  Need to also try this out with terrain as well.  Right now we do a depth mask on the terrain for holes etc which works fine and we were planning on doing that for entrances ie caves etc as well but this approach might be better.

**Comment by gamemachine** [comment] 2018-09-25 00:04
Ya I went this route after struggling with dynamic terrain holes.  Being that you can't get at the terrain geometry it's impossible to make depth masks that fit exactly, leaving gaps that are visible at certain angles.

**Comment by huwb** [comment] 2018-09-25 07:47
Thanks guys. The hole shape could also come from a world aligned texture rather than a procedural square.

Another small addition might be to do the clip in the vertex shader - this is possible by returning NaN in the vertex for the POS. Apparently its undocumented but GPUs support it - they'll discard the vert.

Jeremy Moore talks about this here for punching holes in terrain:
https://www.gdcvault.com/play/1025480/Terrain-Rendering-in-Far-Cry

( This page seems to have died for me but some guy has mirrored it here:
http://www.geeks3d.com/forums/index.php?topic=5381.0 )

This saves the GPU having to do rasterisation and running the pixel shader. However with the dynamically changing mesh density, the bounds of the hole may change slightly, which may be visible depending on the scenario. Just thought I'd throw it in the mix.

**Comment by huwb** [comment] 2018-09-25 07:49
Oh and if the hole can be very rough, simply turning off the meshrenderer's on ocean tiles that are in the hole region is a coarse grain solution. This might for killing ocean tiles underneath a large island and should be readily possible with a C# script (i can elaborate if this sounds interesting).

**Comment by holdingjason** [comment] 2018-09-25 15:47
For us anyway it could be fairly crude so clipping out an area would probably be fine even with the dynamically change mesh since we would just make sure to put in plenty of room.

When you say hole shape @huwb  are you referring to masking it out or clipping as well?  So just away to allow a none rect shape for clipping?

As far as turning off the rendering I think right now the ocean squares are pretty big so not sure that is something that would work.  I know we can reduce those in size but I think that has a significant perf impact but could test that.

**Comment by huwb** [comment] 2018-09-30 10:12
Oops sorry for the delay!

Yeah i was thinking of clipping - sample a low res world aligned texture and clip based on the value, so you can paint holes. Or sampling the texture after transforming the vert in the ocean vert shader, and the vert is in a 'hole region' return NaN from the shader to knock out the vert and surrounding tris.

After rereading i realised i misunderstood the above, and it turns out i did not know what a depth mask is! I've done my homework now and it looks interesting, but I'm not sure how well it works with a surface that moves around i.e. waves. Hmm..

I wonder if there is an accuracy vs expense tradeoff with the techniques roughly in this order:

* Cull tiles so they don't even get submitted if i.e. they are contained within some culling volume - means they never even hit the GPU, but granularity is poor. Could be useful under islands etc.
* Knock out verts in the ocean shader based on an AABB as posted above or a world aligned texture. Gives medium-ish accuracy - the accuracy of the LOD. At some distance away it might knock out large triangles and might be noticeable.
* Depth mask - the gpu would then cull fragments before the fragment shader. Gives potentially high accuracy if you can position your masking shape close to the surface (? - question above)
* Clip in shader - either based on AABB or world aligned texture. Would give an exact hole shape, but requires all of the processing and fragment shader setup.

**Comment by holdingjason** [comment] 2018-10-08 14:20
Sorry to have disappeared having to work on some other non ocean related features for our demo and just now getting some time to play with this again.  So it looks like you made at note on #77 and could not get the shape texture idea working.  Do we have maybe a summary of where we are at?   Thanks

**Comment by huwb** [comment] 2018-10-08 21:59
Sure - regarding #77 I thought i could make a shader that would punch holes into the ocean, by writing NaNs into the displacement textures. However this gets foiled on PC by the way the shader seems to treat NaNs, and actually it was a stupid idea to pump NaNs into a system which might sample this data in many places, including for physics/collision!

So the status is I havent acted on any of the techniques in the breakdown above and dont have immediate plans to right now. I reread the thread to scan for concrete requirements and your first suggestion of just pushing the surface down is a good one. I added it to my last reply above and would happily make a PR if it helps and you think this would solve your problem.

**Comment by holdingjason** [comment] 2018-10-09 14:45
I would say whatever is easiest at this point and that sounds like pushing the ocean down (thought it would work like the shore one where it calms everything down but whatever is best is fine with me).  I agree that we dont really need to worry at this point about optimization since we already have the ocean rendering fully now.  Lets just solve the issue in the easiest way possible and move forward we can always come back latter if needed.  So saying that I can try and dig into the shader and see what would be involved passing in some points where it would lower the y value as you suggested unless its something you can easily pass along.   Thanks and sounds good.  BTW Crest keeps getting better and better all the time its really amazing what you have accomplished.

**Comment by huwb** [comment] 2018-10-09 21:43
I was about to write how easy this kind of thing is and how its what Crest was designed to do, but it turns out pushing the shape down to a set value like this is not so easy to do at all :(. The concept is simple - there are displacement textures and you just need to render a negative displacement wherever you want it (by rendreing into the LODDataAnimatedWaves layer/camera). Unfortunately the way its set up now, it does a combine pass the shape render to combine waves of different frequencies, and if you just naiively render into the shape cams then the combine pass will accumulate multiple copies which causes a few varieties of badness like not getting the exact shape you wanted, and pops when the lods move around. The fix is to render the shape into one specific LOD, and I've opened a pull request with a shader that does this (it checks the lod in the vertex shader and discards the geometry if its not in the selected lod). 

If you assign the material to any geometry, it will pull the water surface to the top of the geometry. I've demo'd it with a sphere slightly above the sea level, and a plane pushed deep below - see main.unity

![image](https://user-images.githubusercontent.com/939901/46700411-ad144880-cc14-11e8-968d-807fed0dd5db.png)

There is a param on the material called Shape Size - this is used to select a LOD. Set it to a large value if you don't need high resolution, so that it will render to a low res LOD, which gives a big view range.

(In the future, it would be possible to do the combine pass before custom shape rendering, so that you could simply render whatever displacements you want and it will Just Work without the above hassle, but it will take a bunch of changes that I'm mulling over at the moment, and perhaps the above PR does the job for now.)

**Comment by eobet** [comment] 2018-10-30 09:33
Can anything discussed here also be used to have a non-water filled interior of a boat, or is that a different feature set?

**Comment by huwb** [comment] 2018-10-30 09:48
Yes absolutely! The shader I added in that PR aligns water to the top of the shape. The shape is rendered from top down. It should be easy to either generate rough geometry that matches the hull of the ship, or fit a simple primitive to the ship and change that shader to render back faces so that it renders the bottom.

**Comment by ibbybn** [comment] 2018-11-04 21:10
I've tried the ShapeSetWaterHeight method and quickly realized it doesn't work for my case. What if you have a submarine which displaces water when on top of the water then go down. The setwaterheight shader will push the water further and further down even when the sub would be under water level. I'm trying to wrap my head around finding a solution which would make the transition between under and above water look good enough. If the view is 3rd person it might be doable this way but what if you look out of the sub through a glass window. I guess masking is the only way then?

**Comment by holdingjason** [comment] 2018-11-04 21:16
Yeah the only way I can think of this working is how we do terrain holes.  We use a sphere or a capsule and apply a depth mask to it.  Can't think of a better way.  Though once your inside the bubble would you not see the water again hmmm

**Comment by huwb** [comment] 2018-11-04 21:31
the mind boggles thinking about the different possibilities here, inside vs outside multiplied by different submarine shapes/structures. one interesting hard case is if your submarine is a glass bubble - in this case you can actually see through it to the water on the other side and you get all kinds of interesting half-submerged views that could be really hard to render (efficiently). 

i think some mixture of the techniques discussed in this thread could work in some situations, and there is a fair bit of flexibility in crest, but ultimately it depends on the many details of the situation.

**Comment by ibbybn** [comment] 2018-11-04 21:56
If you look at the easiest case which would be a quad window and the camera is not angled one could simple just clip only the ocean geometry at a certain distance ( maybe clip fade would look better ? )
Then perhaps it's possible to create a curved/angled clipping plane depending on view and defined shape?

**Comment by huwb** [comment] 2018-11-24 19:06
> I was about to write how easy this kind of thing is and how its what Crest was designed to do, but it turns out pushing the shape down to a set value like this is not so easy to do at all :(. The concept is simple - there are displacement textures and you just need to render a negative displacement wherever you want it (by rendreing into the LODDataAnimatedWaves layer/camera). Unfortunately the way its set up now, it does a combine pass down the LOD chain to combine waves of different frequencies, and if you just naiively render into the shape cams it will render into all lods and then combine them together which will accumulate multiple copies. This causes a few varieties of badness like not getting the exact shape you wanted, and pops when the lods move around. The fix is to render the shape into one specific LOD, and I've opened a pull request (#95) with a shader that does this (it checks the lod in the vertex shader and discards the geometry if its not in the selected lod).

It was a long and windy road but this has finally been massively simplified on latest: 29f404992177cbd9226bf21622b77d9965badb44 . You need only assign the material WaterHeightFromGeometry to your geometry and attach a RegisterAnimWavesInput component and it should just work.

Knowing this was coming online was the primary reason i left this issue open. If theres any thoughts on this let me know, otherwise i'll close this.

**Comment by huwb** [comment] 2018-11-25 09:53
> Can anything discussed here also be used to have a non-water filled interior of a boat, or is that a different feature set?

Also added a shader you can apply to geometry that will subtract it from the surface shape: AnimWavesSubtractGeometry

**Comment by huwb** [comment] 2018-11-27 21:17
I realised ADDing height from geometry is more useful than replacing height, so I made an 'add' variant in the commit reference above.

accidentally made this along the way :)
https://drive.google.com/open?id=1zaSwvZy3NJZWpoXiFgCRRj6VbPVJ19A_

**Comment by moosichu** [comment] 2018-11-27 21:58
@huwb Link is broken, fix:
https://drive.google.com/file/d/1zaSwvZy3NJZWpoXiFgCRRj6VbPVJ19A_/view

**Comment by irshadkarim** [comment] 2018-12-05 20:35
> > Can anything discussed here also be used to have a non-water filled interior of a boat, or is that a different feature set?
> 
> Also added a shader you can apply to geometry that will subtract it from the surface shape: AnimWavesSubtractGeometry
> 
> [5735f1a](https://github.com/huwb/crest-oceanrender/commit/5735f1a00215f6e5a6eeba98d40600dda2ddae1a)

The way these solutions work are really novel. I have been playing around with it a bit though - and I may be missing something (my experience with this kind of simulation is minimal at best) - but from my attempts at using the new shaders, they do exactly what they say. They remove the geometry from the given bounds, but in doing so, if the object in question (like a boat) relies on physics to stay afloat, it sinks a little further. This in turn removes the geometry below, and the boat continues to sink until finally the geometry has had enough and catapults the vessel clear of the ocean.

Also, I did find the resulting hole in the geometry drifts away if you have any sort of wave systems being generated by the  Shape Gerstner Batched component.

All the same, I think your responsiveness here is beyond impressive, and having found this project was a huge relief after considering the quality of those on the asset store.

**Comment by holdingjason** [comment] 2018-12-05 20:49
Have not had a chance to work with this yet but that does make some sense.  I would think in this case we would actually just want to hide/stop renderering the visible elements but maintain the physical elements of the simulation.

**Comment by huwb** [comment] 2018-12-06 09:12
Thanks @irshadkarim ! Yes you're right -_- this is a problem. i start to think about maybe copying physics shape out before this any such custom shaping. i was putting a demo together for something else and it was hard to get boat physics to work well, partly because of this issue, and partly because the boats wake affects its own physics in non-trivial ways, and it may be better to not have the boat affected by its own wake.

However masking could be an elegant solution and is a good thing to look at. I riff'd on your shader above @irshadkarim - firstly i made a version that masked by writing out depth, as @holdingjason suggested above, which seemed to work. however using the alpha channel or the depth may affect other things, and i think i would prefer to use the stencil functionality which may have less collisions depending on the project. However using stencil masking also requires a change to the ocean shader to check for stencil, which could be a toggle on the material. This is an extra thing required to use stencil instead of depth. I'm on the fence about which approach is best at the moment.

I've pushed both depth masking and stencil masking to #137, and enabled it in the main scene on a cube to punch a hole through the surface. it should look like this (by default using stencil masking, but there is a depth masking material as well).

![image](https://user-images.githubusercontent.com/939901/49573675-8170be80-f936-11e8-8bbe-689b6d615f95.png)

Any/all masking approaches should use the new script RegisterMaskInput - this is so the geometry can render in the transparent queue (so it doesnt affect opaque surface rendering in any way), but render before the ocean surface renders which usually renders before anything else transparent.

**Comment by irshadkarim** [comment] 2018-12-06 15:43
That works great! I think the stencil method sounds pretty promising (especially once I had a coworker explain the concept to me, and their flexibility). One area where the alpha method does have a potential advantage is that it's not entirely cutout - by setting the mask's alpha to anything between 0 and 1, you can allow some of the water to render through more transparently, though I'm not actually sure there's any practical use for this. Was just something vaguely interesting I noticed.

Here's what my test boat looks like, using the stencil shader: 
![image](https://user-images.githubusercontent.com/35537356/49593900-167db280-f94b-11e8-8ccf-6fca5195ad9d.png). The inside is bone dry, which is great. Along the side of the benches you can see a bit of the ocean sneaking in, but this was largely expected and is just going to be a matter of tailoring the mask mesh to be identical to the visible mesh, with one critical difference - the outer edges need to be tucked in so water can run up against the sides without being masked.

**Comment by huwb** [comment] 2018-12-08 22:45
Nice, i also made an attempt at something similar and added a rowboat to main.unity in the example content, and I just merged it into master. It seems to work really well in my tests.

I'm closing this one now folks as i feel this particular issue has run its course. If need be i can reopen, or if there are significant bugs or new feature requests lets create new issues. Thanks a bunch for the contributions, i think we landed in a good place with this 👍.

**Comment by huwb** [comment] 2018-12-12 13:38
Soooo it turns out the stencil solution has some critical flaws:

* It will stencil out all water - so you can see the boat interior poking through all waves, even foreground waves that are some distance from the boat! This is pretty fundamental and makes me unexcited about the stencil approach. The alpha-approach (described above) would also suffer from the issue of poking through waves.
* There is a collision with unity's undocumented use of the stencil buffer in the built in pipeline: https://answers.unity.com/questions/956062/unity-5-deferred-stencil-buffer-usage.html , which creates issues like #142 .

My inclination is to remove the stencil buffer masking and leave the depth-based masking. The setup for the depth masking is trivial - assign the OceanMaskUsingDepth material and the RegisterMaskInput script. I've updated the rowboat in main.unity to use this.

If there are any thoughts let me know. I aim to remove the stencil stuff in the next days.

**Comment by b1gry4n** [comment] 2019-12-26 03:19
I just recently picked up the lwrp version on the store. I think being able to cut into the ocean is extremely important and I was surprised crest didnt come with this already since it has almost all the other "required" features an ocean needs. 

Ceto is now open source and could provide a bit of insight into how this could be done (https://github.com/Scrawk/Ceto) I guess it has been for a while but I only just recently found out. The way cutting holes in the ocean is done in ceto is pretty much perfect and if this feature is implemented in crest I would hope it is done in a similar way. Personally I just want to be able to go into the underbelly of a ship which would require the water to be cut and disabled even if my camera cannot see the stencil shader.

![image](https://user-images.githubusercontent.com/5430180/71455400-51fb4280-2741-11ea-98be-21cf605f4605.png)

You supply the tool with an alpha mask texture. The bounding box represents the textures dimensions in the world. In the case of the image above the cutout texture is the default unity particle image. In the affected area the verts arent drawn, this is apparent if you get very close to the cut or if you enter wire frame mode. The underwater effect is disabled if your camera is directly under the cutout space and is reenabled when you cross into an area that isnt cut out (still inside the bounding shape)

Removing verts could be messy at a distance with the LOD system as mentioned above. This is only an issue if you need to have these holes visible from a distance. Something like cutting into the ocean from the inside of a boat could benefit from its own LOD system. I would imagine the cutout could be disabled until the camera gets within a certain distance so that you dont see giant missing triangles on the horizon.

**Comment by huwb** [comment] 2019-12-28 18:06
Thanks for the pointer.

We could potentially add culling mask data. This won't happen in the very short term but i'll reopen this to catch any findings.

**Comment by huwb** [comment] 2020-01-05 18:00
Experiment started here: https://github.com/crest-ocean/crest/tree/feature/clip-surface-data

Looks promising on built-in RP. Need to evaluate prospects on URP/HDRP.

**Comment by huwb** [comment] 2020-01-12 15:05
@daleeidd and I merged PR #396 into master which implements a similar idea to what @b1gry4n describes above, in a way that fits into our system.

Example uses of this in main.unity (*Rowboat* object has clipsurface inputs) and boat.unity (see *FloatingOpenContainer* object).

Notes added to userguide.md.

Feedback welcome!

**Closed** 2020-03-07 17:41 UTC
Labels: question
